# Generated by Django 5.2.15 on 2026-08-05 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.CharField(choices=[('core', 'Core Team'), ('finance', 'Finance'), ('food', 'Food'), ('hospitality', 'Hospitality'), ('event', 'Event'), ('program', 'Program'), ('cultural', 'Cultural'), ('publicity', 'Publicity'), ('invitation', 'Invitation'), ('verification', 'Verification Volunteer')], default='core', max_length=32)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff profile',
                'verbose_name_plural': 'Staff profiles',
            },
        ),
    ]
