# Generated by Django 5.2.15 on 2026-08-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_staff_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Force password change after login (set True when seeding).'),
        ),
    ]
