# Generated by Django 5.2.15 on 2026-09-04 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_must_change_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='committee',
            field=models.CharField(choices=[('core', 'Core Team'), ('finance', 'Finance'), ('food', 'Food'), ('hospitality', 'Hospitality'), ('event', 'Event'), ('program', 'Program'), ('cultural', 'Cultural'), ('publicity', 'Publicity'), ('invitation', 'Invitation'), ('verification', 'Verification Volunteer'), ('judge', 'Judge / Jury'), ('volunteer', 'Volunteer'), ('coordinator', 'Faculty / Event Coordinator')], default='core', max_length=32),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(blank=True, max_length=80)),
                ('resource_id', models.CharField(blank=True, max_length=60)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
