# Generated by Django 5.2.15 on 2026-07-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('tech', 'Tech'), ('arts', 'Arts'), ('sports', 'Sports'), ('management', 'Management'), ('general', 'General')], default='general', max_length=50)),
                ('description', models.TextField()),
                ('rules', models.TextField(blank=True)),
                ('venue', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('max_participants', models.PositiveIntegerField(default=100)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('is_registration_open', models.BooleanField(default=True)),
                ('is_result_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
