# Generated by Django 5.2.15 on 2026-08-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_banner_image_event_coordinator_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='audience',
            field=models.CharField(blank=True, choices=[('school', 'School Day'), ('college', 'College Day')], default='', help_text='School Day vs College Day audience. Blank for legacy/test events.', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='event_end_time',
            field=models.TimeField(blank=True, help_text='End time when officially scheduled.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='prize_pool',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Official prize pool in ₹. Leave blank when not announced.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='department',
            field=models.CharField(blank=True, help_text='College zone (e.g. Tech Zone) or school classification (e.g. Major Attraction).', max_length=120),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, help_text='Start time. Leave blank when schedule is TBD / unscheduled.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
