# Generated by Django 5.2.15 on 2026-09-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_prize_end_audience'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_registration_open', 'status'], name='events_even_is_regi_55a60a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_date'], name='events_even_event_d_2c2da5_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['audience'], name='events_even_audienc_54e946_idx'),
        ),
    ]
