# Generated by Django 5.2.15 on 2026-08-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('general', 'General Festival Highlights'), ('cultural', 'Cultural & Pro-Show'), ('technical', 'Technical Competitions'), ('gaming', 'Esports & Gaming'), ('pro-show', 'Celebrity & Pro-Shows')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Cover image for video items (optional)', null=True, upload_to='gallery/thumbs/'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='type',
            field=models.CharField(choices=[('image', 'Image / Photo'), ('video', 'Video / Reel')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='video_url',
            field=models.CharField(blank=True, default='', help_text='YouTube URL / embed link or server file path for video type', max_length=500),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
