# Generated by Django 5.2.15 on 2026-08-05 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_banner_image_event_coordinator_email_and_more'),
        ('registrations', '0002_registration_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('college_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='registration',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='food_preference',
            field=models.CharField(choices=[('none', 'None'), ('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='needs_accommodation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='needs_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_receipt_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='registration',
            name='transport_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registration',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='waitlist_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('waived', 'Waived')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['event', 'is_waiting_list'], name='registratio_event_i_a9091d_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['registration_number'], name='registratio_registr_40a794_idx'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='registrations.registration'),
        ),
    ]
