# Generated by Django 5.2.15 on 2026-08-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_future_enhancements_ops'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='accommodation_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='accommodation_notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registration',
            name='food_notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='food_preference',
            field=models.CharField(choices=[('none', 'None'), ('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('jain', 'Jain')], default='none', max_length=20),
        ),
    ]
