# Generated by Django 5.2.15 on 2026-08-13 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_production_ops_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='accommodation_hostel',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='registration',
            name='accommodation_room',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='registration',
            name='accommodation_status',
            field=models.CharField(choices=[('none', 'Not required'), ('pending', 'Pending allocation'), ('allocated', 'Allocated'), ('checked_in', 'Checked in'), ('checked_out', 'Checked out')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(blank=True, choices=[('unspecified', 'Prefer not to say'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='unspecified', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='registrations/payment_proof/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_verifications_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
