# Generated by Django 5.2.15 on 2026-08-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('refunded', 'Refunded'), ('waived', 'Waived')], default='pending', max_length=20),
        ),
    ]
