# Generated by Django 5.2.15 on 2026-09-02 15:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_alter_registration_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='department',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='registration',
            name='register_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teammember',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='attendance_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammember',
            name='department',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='teammember',
            name='finance_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='finance_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='finance_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_finance_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammember',
            name='gender',
            field=models.CharField(blank=True, default='unspecified', max_length=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='invitation_status',
            field=models.CharField(choices=[('pending', 'Invitation Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='accepted', max_length=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='invited_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teammember',
            name='organizer_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='organizer_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='organizer_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_organizer_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammember',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='payment_method',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='teammember',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='team_members/payment_proof/'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='payment_rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teammember',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('refunded', 'Refunded'), ('waived', 'Waived')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='teammember',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='payment_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_payment_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team_members/photos/'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='qr_pass_code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='register_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('captain', 'Captain'), ('member', 'Member')], default='member', max_length=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
