# Generated by Django 5.2.15 on 2026-09-03 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_registration_department_registration_register_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='event_attendance_marked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='event_attended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='event_attended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_attendances_marked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='verification_attendance_marked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='teammember',
            name='event_attendance_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammember',
            name='event_attended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='verification_attendance_marked',
            field=models.BooleanField(default=False),
        ),
    ]
