# Generated by Django 5.2.15 on 2026-09-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_registration_event_attendance_marked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(blank=True, choices=[('unspecified', 'Prefer not to say'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('others', 'Others')], default='unspecified', max_length=20),
        ),
    ]
