# Generated by Django 5.2.15 on 2026-09-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_registration_refund_amount_registration_refund_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('refunded', 'Refunded'), ('waived', 'Waived')], db_index=True, default='pending', max_length=20),
        ),
    ]
