# Generated by Django 5.2.15 on 2026-09-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_alter_registration_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked after payment confirmation to freeze team details.'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('refunded', 'Refunded'), ('waived', 'Waived')], db_index=True, default='pending', max_length=20),
        ),
    ]
