# Generated by Django 5.2.15 on 2026-09-07 01:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_events_even_is_regi_55a60a_idx_and_more'),
        ('registrations', '0014_registration_is_locked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['user', 'cancelled_at'], name='registratio_user_id_35592d_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['-registered_at'], name='registratio_registe_116d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['payment_status', 'cancelled_at'], name='registratio_payment_4bfb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['registration', 'role'], name='registratio_registr_eb9e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['email'], name='registratio_email_d39074_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['invitation_status'], name='registratio_invitat_a57cab_idx'),
        ),
    ]
