# Generated by Django 5.2.15 on 2026-08-24 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Mens Hostel'), ('female', 'Ladies Hostel'), ('all', 'All Delegates / Co-ed')], default='male', max_length=20)),
                ('hostel_type', models.CharField(default='Campus Hostel', max_length=100)),
                ('location', models.CharField(default='MACFAST Campus', max_length=200)),
                ('distance', models.CharField(default='2 min walk to Fest Arena', max_length=100)),
                ('tariff_per_night', models.DecimalField(decimal_places=2, default=250.0, max_digits=8)),
                ('room_types', models.CharField(default='Twin Sharing, 4-Sharing Dormitory', max_length=255)),
                ('amenities', models.TextField(default='Free Wi-Fi, 24/7 Security & CCTV, Hot Water, Filter Drinking Water, Mess Breakfast Included')),
                ('warden_name', models.CharField(max_length=120)),
                ('warden_phone', models.CharField(max_length=30)),
                ('total_capacity', models.PositiveIntegerField(default=100)),
                ('available_beds', models.PositiveIntegerField(default=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=20)),
                ('persons_count', models.PositiveSmallIntegerField(default=1)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Allocation'), ('confirmed', 'Confirmed'), ('allocated', 'Allocated Room'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('allocated_hostel', models.CharField(blank=True, max_length=150)),
                ('allocated_room', models.CharField(blank=True, max_length=60)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodation_bookings', to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accommodation.hostel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
