# Generated by Django 5.2.15 on 2026-09-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationbooking',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='accommodationbooking',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='accommodation/payment_proof/'),
        ),
        migrations.AddField(
            model_name='accommodationbooking',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='accommodationbooking',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
