# Generated by Django 5.2.15 on 2026-09-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_accommodationbooking_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationbooking',
            name='payment_method',
            field=models.CharField(blank=True, default='upi_qr', max_length=40),
        ),
        migrations.AlterField(
            model_name='accommodationbooking',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=350.0, max_digits=10),
        ),
    ]
