# Generated by Django 5.2.15 on 2026-09-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_accommodationbooking_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationbooking',
            name='include_breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accommodationbooking',
            name='include_dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accommodationbooking',
            name='include_lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='tariff_per_night',
            field=models.DecimalField(decimal_places=2, default=350.0, max_digits=8),
        ),
    ]
