import {
  getHighlights, createHighlight, updateHighlight, deleteHighlight, getHighlight,
  getCategoryContents, createCategoryContent, updateCategoryContent, deleteCategoryContent, getCategoryContent,
  getEventFormats, createEventFormat, updateEventFormat, deleteEventFormat, getEventFormat,
  getGuestProfiles, createGuestProfile, updateGuestProfile, deleteGuestProfile, getGuestProfile,
  getTestimonials, createTestimonial, updateTestimonial, deleteTestimonial, getTestimonial,
  getFAQs, createFAQ, updateFAQ, deleteFAQ, getFAQ,
  getSponsors, createSponsor, updateSponsor, deleteSponsor, getSponsor,
  getFestRewindItems, createFestRewindItem, updateFestRewindItem, deleteFestRewindItem, getFestRewindItem,
} from "../../../services/api";

export const CMS_RESOURCES = {
  highlights: {
    title: "Festival Highlights",
    singular: "Highlight",
    basePath: "/admin/content/highlights",
    listColumns: [{ key: "title", label: "Title" }, { key: "order", label: "Order" }],
    searchFields: ["title", "description"],
    api: { list: () => getHighlights(true), get: getHighlight, create: createHighlight, update: updateHighlight, delete: deleteHighlight },
    fields: [
      { name: "icon", label: "Icon (emoji)", type: "text" },
      { name: "title", label: "Title *", type: "text", required: true },
      { name: "description", label: "Description *", type: "textarea", required: true },
      { name: "order", label: "Order", type: "number" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
    empty: { icon: "✨", title: "", description: "", order: 0, is_active: true },
  },
  categories: {
    title: "Homepage Categories",
    singular: "Category",
    basePath: "/admin/content/categories",
    listColumns: [{ key: "name", label: "Name" }, { key: "order", label: "Order" }],
    searchFields: ["name", "description"],
    api: { list: () => getCategoryContents(true), get: getCategoryContent, create: createCategoryContent, update: updateCategoryContent, delete: deleteCategoryContent },
    fields: [
      { name: "name", label: "Name *", type: "text", required: true },
      { name: "icon", label: "Icon", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "image", label: "Image", type: "image" },
      { name: "order", label: "Order", type: "number" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
    empty: { name: "", icon: "", description: "", order: 0, is_active: true },
  },
  formats: {
    title: "Event Formats",
    singular: "Format",
    basePath: "/admin/content/formats",
    listColumns: [{ key: "title", label: "Title" }, { key: "label", label: "Label" }],
    searchFields: ["title", "description"],
    api: { list: () => getEventFormats(true), get: getEventFormat, create: createEventFormat, update: updateEventFormat, delete: deleteEventFormat },
    fields: [
      { name: "label", label: "Label (1, 2, 3, 4, ∞) *", type: "text", required: true },
      { name: "title", label: "Title *", type: "text", required: true },
      { name: "description", label: "Description *", type: "textarea", required: true },
      { name: "order", label: "Order", type: "number" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
    empty: { label: "1", title: "", description: "", order: 0, is_active: true },
  },
  guests: {
    title: "Guest Profiles",
    singular: "Guest",
    basePath: "/admin/content/guests",
    listColumns: [{ key: "name", label: "Name" }, { key: "role", label: "Role" }],
    searchFields: ["name", "role", "description"],
    api: { list: () => getGuestProfiles(true), get: getGuestProfile, create: createGuestProfile, update: updateGuestProfile, delete: deleteGuestProfile },
    fields: [
      { name: "name", label: "Name *", type: "text", required: true },
      { name: "role", label: "Role *", type: "text", required: true },
      { name: "description", label: "Description *", type: "textarea", required: true },
      { name: "image", label: "Photo", type: "image" },
      { name: "order", label: "Order", type: "number" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
    empty: { name: "", role: "", description: "", order: 0, is_active: true },
  },
  testimonials: {
    title: "Testimonials",
    singular: "Testimonial",
    basePath: "/admin/content/testimonials",
    listColumns: [{ key: "name", label: "Name" }, { key: "role", label: "Role" }],
    searchFields: ["quote", "name", "role"],
    api: { list: () => getTestimonials(true), get: getTestimonial, create: createTestimonial, update: updateTestimonial, delete: deleteTestimonial },
    fields: [
      { name: "quote", label: "Quote *", type: "textarea", required: true },
      { name: "name", label: "Name *", type: "text", required: true },
      { name: "role", label: "Role", type: "text" },
      { name: "order", label: "Order", type: "number" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
    empty: { quote: "", name: "", role: "", order: 0, is_active: true },
  },
  faqs: {
    title: "FAQ",
    singular: "FAQ",
    basePath: "/admin/content/faqs",
    listColumns: [{ key: "question", label: "Question" }],
    searchFields: ["question", "answer"],
    api: { list: () => getFAQs(true), get: getFAQ, create: createFAQ, update: updateFAQ, delete: deleteFAQ },
    fields: [
      { name: "question", label: "Question *", type: "text", required: true },
      { name: "answer", label: "Answer *", type: "textarea", required: true },
      { name: "order", label: "Order", type: "number" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
    empty: { question: "", answer: "", order: 0, is_active: true },
  },
  sponsors: {
    title: "Sponsors",
    singular: "Sponsor",
    basePath: "/admin/content/sponsors",
    listColumns: [{ key: "name", label: "Name" }, { key: "sponsor_type", label: "Type" }],
    searchFields: ["name", "sponsor_type"],
    api: { list: () => getSponsors(true), get: getSponsor, create: createSponsor, update: updateSponsor, delete: deleteSponsor },
    fields: [
      { name: "name", label: "Name *", type: "text", required: true },
      {
        name: "sponsor_type", label: "Type *", type: "select", required: true,
        options: ["Host", "Title", "Gold", "Silver", "Partner", "Media"].map((v) => ({ value: v, label: v })),
      },
      { name: "website", label: "Website", type: "text" },
      { name: "logo", label: "Logo", type: "image" },
      { name: "order", label: "Order", type: "number" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
    empty: { name: "", sponsor_type: "Partner", website: "", order: 0, is_active: true },
  },
  rewind: {
    title: "Fest Rewind",
    singular: "Rewind tile",
    basePath: "/admin/content/rewind",
    listColumns: [{ key: "title", label: "Title" }, { key: "order", label: "Order" }],
    searchFields: ["title"],
    api: {
      list: () => getFestRewindItems(true),
      get: getFestRewindItem,
      create: createFestRewindItem,
      update: updateFestRewindItem,
      delete: deleteFestRewindItem,
    },
    fields: [
      { name: "title", label: "Title *", type: "text", required: true },
      { name: "image", label: "Photo", type: "image" },
      { name: "order", label: "Order", type: "number" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
    empty: { title: "", order: 0, is_active: true },
  },
};

export const CMS_DASHBOARD_CARDS = [
  { title: "Site Settings, Hero & Branding", desc: "Fest name, dates, hero copy, contact, images", href: "/admin/content/site-settings" },
  { title: "Homepage Sections", desc: "Show/hide sections and edit titles", href: "/admin/content/homepage-sections" },
  { title: "Highlights", desc: "Festival highlight cards on homepage", href: "/admin/content/highlights" },
  { title: "Event Categories", desc: "Homepage category display cards", href: "/admin/content/categories" },
  { title: "Event Formats", desc: "Solo, duo, trio format section", href: "/admin/content/formats" },
  { title: "Theme", desc: "This year's theme banner", href: "/admin/content/theme" },
  { title: "Guest Profiles", desc: "Star guest cards and bios", href: "/admin/content/guests" },
  { title: "Testimonials", desc: "Delegate and coordinator quotes", href: "/admin/content/testimonials" },
  { title: "FAQ", desc: "Frequently asked questions", href: "/admin/content/faqs" },
  { title: "Sponsors", desc: "Partner and sponsor listings", href: "/admin/content/sponsors" },
  { title: "Fest Rewind", desc: "Homepage rewind photo tiles", href: "/admin/content/rewind" },
];
