# Generated by Django 5.2.15 on 2026-07-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestRewindItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/rewind/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fest rewind item',
                'verbose_name_plural': 'Fest rewind items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='countdown_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_copyright',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
