# Generated by Django 5.2.15 on 2026-07-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_festrewinditem_sitesetting_countdown_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='cms/brand/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='terms_body',
            field=models.TextField(blank=True),
        ),
    ]
