# Generated by Django 5.2.15 on 2026-07-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_sitesetting_logo_image_sitesetting_terms_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='privacy_body',
            field=models.TextField(blank=True),
        ),
    ]
