# Generated by Django 5.2.15 on 2026-09-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_sitesetting_privacy_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cms/coordinators/')),
                ('is_core', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Coordinator profile',
                'verbose_name_plural': 'Coordinator profiles',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FestivalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('school', 'School Missions (Day 1)'), ('college', 'College Missions (Day 2)'), ('general', 'General Regulations'), ('fairness', 'Fair Play & Ethics'), ('safety', 'Safety & Campus Code')], default='general', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Festival rule',
                'verbose_name_plural': 'Festival rules',
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='brochure_file',
            field=models.FileField(blank=True, null=True, upload_to='cms/brochure/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='brochure_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(blank=True, default='macfiesta@macfast.org', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://www.facebook.com/macfastofficial/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://www.instagram.com/macfiestaofficial/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='official_website',
            field=models.URLField(blank=True, default='https://macfast.org/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='youtube_url',
            field=models.URLField(blank=True, default='https://www.youtube.com/@macfastofficial161'),
        ),
    ]
