# Generated by Django 5.2.15 on 2026-09-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_coordinatorprofile_festivalrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='is_registration_open',
            field=models.BooleanField(default=True, help_text='Allow participants to create new accounts and register for events.'),
        ),
    ]
