# Generated by Django 5.2.15 on 2026-09-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0006_sitesetting_is_registration_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="is_maintenance_mode",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, the public site shows the maintenance screen.",
            ),
        ),
    ]
