/* ===================================================================
   MACFIESTA 2K26 — OFFICIAL EVENTS & MISSIONS DIRECTORY
   14 College Events (₹1,15,000 Pool) + 9 School Events (₹28,000+ Pool)
   Preserved exactly from reference project C:\Users\joels\Desktop\MACFIESTA
   =================================================================== */

export const ALL_OFFICIAL_EVENTS = [
  // ─── COLLEGE EVENTS (14 EVENTS) ──────────────────────────────────
  {
    id: 1,
    title: "Avengers: Code Assemble",
    slug: "avengers-code-assemble",
    subtitle: "Vibe Coding Hackathon",
    description: "Form your supreme development alliance and engineer disruptive, AI-infused software solutions to solve real-world industry crisis briefs.",
    audience: "college",
    category: "technical",
    type: "squad",
    registration_fee: 200,
    prize_pool: 15000,
    difficulty: "expert",
    max_participants: 25,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "10:00:00",
    venue: "Stark Innovation Labs (MCA Block)",
    image: "/MARVEL/4081455907815375.png",
    hero: "Iron Man & Avengers",
    level: "Level: Alpha",
    powerRating: "Power: 99/100",
    accentColor: "#ED1D24",
    is_registration_open: true,
    coordinator_name: "Prof. Rajesh Kumar",
    coordinator_phone: "+91 94470 11111",
    coordinator_email: "rajesh@macfast.org",
    rules: [
      "Team size: 2 to 4 members from recognized colleges/universities.",
      "Projects must be built during the hackathon. Pre-existing codebases are disqualified.",
      "Public GitHub repository commits and live deployment are mandatory for jury evaluation.",
      "Judging criteria: Innovation (30%), Architecture (30%), UI/UX (20%), Defense (20%)."
    ]
  },
  {
    id: 2,
    title: "The Flash: Code Rush",
    slug: "the-flash-code-rush",
    subtitle: "Coding Challenge",
    description: "Race against the Speed Force in high-octane algorithmic problem sets, rapid debugging sprints, and extreme syntax warfare.",
    audience: "college",
    category: "technical",
    type: "solo",
    registration_fee: 100,
    prize_pool: 5000,
    difficulty: "hard",
    max_participants: 40,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "10:00:00",
    venue: "Turing Lab 2",
    image: "/MARVEL/61080138757668761.png",
    hero: "The Flash",
    level: "Level: Speedster",
    powerRating: "Power: 96/100",
    accentColor: "#FFD700",
    is_registration_open: true,
    coordinator_name: "Ananya Nair",
    coordinator_phone: "+91 94470 22222",
    coordinator_email: "ananya@macfast.org",
    rules: [
      "Individual participation only.",
      "Languages supported: C, C++, Java, Python, JavaScript.",
      "Score is calculated based on execution speed, test cases cleared, and memory efficiency.",
      "No internet browsing or AI assistants allowed during active coding phases."
    ]
  },
  {
    id: 3,
    title: "Battle of Wakanda",
    slug: "battle-of-wakanda",
    subtitle: "BGMI Battlegrounds",
    description: "Drop onto the battleground with your elite squad and conquer tactical battle zones to claim the Vibranium Championship Trophy.",
    audience: "college",
    category: "gaming",
    type: "squad",
    registration_fee: 200,
    prize_pool: 7000,
    difficulty: "expert",
    max_participants: 20,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "10:00:00",
    venue: "Asgard Esports Lounge",
    image: "/MARVEL/Spider-man.png",
    hero: "Black Panther",
    level: "Level: Vibranium",
    powerRating: "Power: 98/100",
    accentColor: "#7B2FBE",
    is_registration_open: true,
    coordinator_name: "Kiran Kumar",
    coordinator_phone: "+91 94470 33333",
    coordinator_email: "kiran@macfast.org",
    rules: [
      "Squad participation (4 players + 1 optional sub).",
      "Mobile devices only. Emulators, iPads, triggers, and third-party tools are banned.",
      "Custom room matches across Erangel, Miramar, and Sanhok.",
      "Points awarded based on official BGMI tournament placement and kill multipliers."
    ]
  },
  {
    id: 4,
    title: "Justice League: Ultimate XI",
    slug: "justice-league-ultimate-xi",
    subtitle: "EFootball Tournament",
    description: "Take command of football titans in head-to-head console and mobile matches. Outwit rival managers and score your way to victory.",
    audience: "college",
    category: "gaming",
    type: "solo",
    registration_fee: 100,
    prize_pool: 7000,
    difficulty: "hard",
    max_participants: 32,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "10:00:00",
    venue: "Esports Arena Console Zone",
    image: "/MARVEL/3025924746959430.jpg",
    hero: "Justice League",
    level: "Level: League",
    powerRating: "Power: 95/100",
    accentColor: "#00D4FF",
    is_registration_open: true,
    coordinator_name: "Abhijith R.",
    coordinator_phone: "+91 94470 44444",
    coordinator_email: "abhijith@macfast.org",
    rules: [
      "Single elimination knockout bracket.",
      "Match duration: 10 minutes (Extra time and penalties apply on draw).",
      "Authentic clubs & standard team ratings enabled.",
      "Disconnection or intentional stalling leads to forfeit."
    ]
  },
  {
    id: 5,
    title: "Stark Industries: The Pitch",
    slug: "stark-industries-the-pitch",
    subtitle: "Shark Tank & Startup Pitch",
    description: "Step into the boardroom and pitch breakthrough business models, AI innovations, and venture concepts before seasoned venture investors.",
    audience: "college",
    category: "management",
    type: "duo",
    registration_fee: 150,
    prize_pool: 15000,
    difficulty: "expert",
    max_participants: 16,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "10:00:00",
    venue: "MBA Executive Boardroom",
    image: "/MARVEL/300685712645038155.png",
    hero: "Tony Stark",
    level: "Level: Billionaire",
    powerRating: "Power: 98/100",
    accentColor: "#FFD700",
    is_registration_open: true,
    coordinator_name: "Prof. Priya Nair",
    coordinator_phone: "+91 94470 55555",
    coordinator_email: "priya@macfast.org",
    rules: [
      "Team size: 1 to 3 delegates.",
      "Pitch deck presentation: 6 minutes + 4 minutes Q&A cross-examination.",
      "Must include business model canvas, revenue stream, TAM/SAM, and prototype/deck.",
      "Panel decision regarding valuations and prize distribution is final."
    ]
  },
  {
    id: 6,
    title: "Spider-Verse: Frame Hunt",
    slug: "spider-verse-frame-hunt",
    subtitle: "Photography Competition",
    description: "Capture the vibrant soul, energy, and heroic encounters across MACFIESTA through artistic framing, lighting, and storytelling.",
    audience: "college",
    category: "general",
    type: "solo",
    registration_fee: 100,
    prize_pool: 5000,
    difficulty: "medium",
    max_participants: 30,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "10:00:00",
    venue: "Campus Wide Visual Spots",
    image: "/MARVEL/The Spider….jpg",
    hero: "Spider-Man",
    level: "Level: Shutter",
    powerRating: "Power: 94/100",
    accentColor: "#ED1D24",
    is_registration_open: true,
    coordinator_name: "Siddharth Menon",
    coordinator_phone: "+91 94470 66666",
    coordinator_email: "siddharth@macfast.org",
    rules: [
      "All photos must be captured on MACFAST campus during festival hours.",
      "DSLR, Mirrorless, and high-end smartphone entries accepted in original RAW/JPEG.",
      "Minor post-processing allowed. AI-generation is strictly banned.",
      "Submission deadline: 4:00 PM on Day 1."
    ]
  },
  {
    id: 7,
    title: "Deadpool: Reel Chaos",
    slug: "deadpool-reel-chaos",
    subtitle: "Reels Competition",
    description: "Break the fourth wall and create viral, high-voltage short-form video reels that capture the wildest moments and humorous chaos of the fest.",
    audience: "college",
    category: "general",
    type: "duo",
    registration_fee: 100,
    prize_pool: 5000,
    difficulty: "medium",
    max_participants: 25,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "10:00:00",
    venue: "Festival Ground Studios",
    image: "/MARVEL/Doctor Strange.png",
    hero: "Deadpool",
    level: "Level: Viral",
    powerRating: "Power: 93/100",
    accentColor: "#ED1D24",
    is_registration_open: true,
    coordinator_name: "Rahul E.",
    coordinator_phone: "+91 94470 77777",
    coordinator_email: "rahul@macfast.org",
    rules: [
      "Duration: 30 to 60 seconds (9:16 vertical format).",
      "Must incorporate official festival hashtags and audio tags.",
      "Judging based on creativity, editing flow, engagement, and humor.",
      "Content must respect college campus decorum."
    ]
  },
  {
    id: 8,
    title: "S.H.I.E.L.D. Case Files",
    slug: "shield-case-files",
    subtitle: "Corporate Case Study",
    description: "Crack intricate business crises, forensic management dilemmas, and turnaround strategies as an elite operative.",
    audience: "college",
    category: "management",
    type: "squad",
    registration_fee: 100,
    prize_pool: 7000,
    difficulty: "hard",
    max_participants: 20,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "10:00:00",
    venue: "Corporate Analysis Suite",
    image: "/MARVEL/658651514296997716.png",
    hero: "Nick Fury",
    level: "Level: Director",
    powerRating: "Power: 96/100",
    accentColor: "#00D4FF",
    is_registration_open: true,
    coordinator_name: "Dr. Mathew John",
    coordinator_phone: "+91 94470 88888",
    coordinator_email: "mathew@macfast.org",
    rules: [
      "Team of 2 to 4 members.",
      "Case study distributed 60 minutes prior to jury defense.",
      "Presentation duration: 8 minutes + 4 minutes interrogation.",
      "Emphasis on feasibility, ROI, and crisis resolution speed."
    ]
  },
  {
    id: 9,
    title: "X-Men: Talent Protocol",
    slug: "x-men-talent-protocol",
    subtitle: "Best Manager & Personality",
    description: "Endure grueling stress interviews, psychometric evaluations, crisis management, and charismatic spotlight tasks to be crowned the Supreme Leader.",
    audience: "college",
    category: "management",
    type: "solo",
    registration_fee: 100,
    prize_pool: 8000,
    difficulty: "expert",
    max_participants: 20,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "10:00:00",
    venue: "Auditorium Main Stage",
    image: "/MARVEL/300685712645038155.png",
    hero: "Professor X",
    level: "Level: Omega",
    powerRating: "Power: 99/100",
    accentColor: "#FFD700",
    is_registration_open: true,
    coordinator_name: "Prof. Saji George",
    coordinator_phone: "+91 94470 99999",
    coordinator_email: "saji@macfast.org",
    rules: [
      "Solo entry only.",
      "Multiple rounds: Aptitude, Group Discussion, Stress Interview, Public Address.",
      "Participants must adhere strictly to corporate formal attire.",
      "Elimination after every progressive stage."
    ]
  },
  {
    id: 10,
    title: "Choreo-Verse: The Dance Battle",
    slug: "choreo-verse-the-dance-battle",
    subtitle: "Western Group Dance",
    description: "Ignite the grand festival stage with explosive synchrony, theatrical acrobatics, and pulse-pounding rhythm to claim the national choreography crown.",
    audience: "college",
    category: "cultural",
    type: "group",
    registration_fee: 300,
    prize_pool: 20000,
    difficulty: "expert",
    max_participants: 15,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "04:30:00",
    venue: "Main Open Air Arena",
    image: "/MARVEL/peakpx.png",
    hero: "Scarlet Witch",
    level: "Level: Mystical",
    powerRating: "Power: 99/100",
    accentColor: "#ED1D24",
    is_registration_open: true,
    coordinator_name: "Prof. Arun Kurian",
    coordinator_phone: "+91 94471 00000",
    coordinator_email: "arun@macfast.org",
    rules: [
      "Team size: 6 to 15 performers.",
      "Performance duration: 8 to 12 minutes (including stage setup).",
      "Soundtrack must be provided on USB drive in MP3 format 1 hour prior to call-time.",
      "Judging criteria: Choreography, Synchronization, Costumes, Stage Utilization."
    ]
  },
  {
    id: 11,
    title: "Marvel Trivia: Eye of Agamotto",
    slug: "marvel-trivia-eye-of-agamotto",
    subtitle: "Mega Pop Culture & Marvel Quiz",
    description: "Test your encyclopedic mastery across the Marvel Cinematic Multiverse, DC Universe, anime realms, and sci-fi lore.",
    audience: "college",
    category: "general",
    type: "duo",
    registration_fee: 100,
    prize_pool: 5000,
    difficulty: "hard",
    max_participants: 30,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "10:00:00",
    venue: "Main Seminar Hall",
    image: "/MARVEL/Doctor Strange.png",
    hero: "Doctor Strange",
    level: "Level: Sorcerer",
    powerRating: "Power: 95/100",
    accentColor: "#10B981",
    is_registration_open: true,
    coordinator_name: "Dr. Thomas Varghese",
    coordinator_phone: "+91 94471 11222",
    coordinator_email: "thomas@macfast.org",
    rules: [
      "Teams of 2 delegates.",
      "Preliminary written buzzer round followed by Top 6 Stage Finale.",
      "Pounce and pass rules apply during finals.",
      "Quizmaster's ruling is conclusive on all disputes."
    ]
  },
  {
    id: 12,
    title: "Arkham Asylum: Detective Mystery",
    slug: "arkham-asylum-detective-mystery",
    subtitle: "Treasure Hunt & Crime Scene",
    description: "Decode cryptographic ciphers, analyze physical forensic clues across campus, and solve the grand noir conspiracy.",
    audience: "college",
    category: "general",
    type: "squad",
    registration_fee: 100,
    prize_pool: 6000,
    difficulty: "hard",
    max_participants: 25,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "10:00:00",
    venue: "Campus Wide Crime Zones",
    image: "/MARVEL/658651514296997716.png",
    hero: "Batman",
    level: "Level: Dark Knight",
    powerRating: "Power: 97/100",
    accentColor: "#00D4FF",
    is_registration_open: true,
    coordinator_name: "Prof. Susan Kurian",
    coordinator_phone: "+91 94471 22333",
    coordinator_email: "susan@macfast.org",
    rules: [
      "Team of 3 or 4 operatives.",
      "Clues spread across specified campus quadrants.",
      "Splitting up is permitted; physical violence or vandalism causes instant disqualification.",
      "First team to unlock the final vault box wins."
    ]
  },
  {
    id: 13,
    title: "Wolverine: Street Arm Wrestling",
    slug: "wolverine-street-arm-wrestling",
    subtitle: "Power & Grip Championship",
    description: "Raw strength, tendon power, and adamantium grit. Step up to the official arm wrestling podium and take down opponents.",
    audience: "college",
    category: "sports",
    type: "solo",
    registration_fee: 50,
    prize_pool: 3000,
    difficulty: "medium",
    max_participants: 32,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "10:00:00",
    venue: "Arena Courtyard",
    image: "/MARVEL/61080138757668761.png",
    hero: "Wolverine",
    level: "Level: Adamantium",
    powerRating: "Power: 92/100",
    accentColor: "#FF8C00",
    is_registration_open: true,
    coordinator_name: "Jomon V.",
    coordinator_phone: "+91 94471 33444",
    coordinator_email: "jomon@macfast.org",
    rules: [
      "Individual weight category matches (Under 75kg and Open).",
      "Standard World Armwrestling Federation (WAF) referee rules enforced.",
      "Two fouls lead to match loss.",
      "Double elimination tournament structure."
    ]
  },
  {
    id: 14,
    title: "Thor's Penalty Shootout",
    slug: "thors-penalty-shootout",
    subtitle: "Sudden Death Penalty Arena",
    description: "Channel the power of Mjolnir in high-pressure 1v1 penalty strikes. Beat the goalkeeper and claim the spot kick trophy.",
    audience: "college",
    category: "sports",
    type: "solo",
    registration_fee: 50,
    prize_pool: 4000,
    difficulty: "medium",
    max_participants: 32,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "10:00:00",
    venue: "Athletic Grounds Turf Arena",
    image: "/MARVEL/3025924746959430.jpg",
    hero: "Thor",
    level: "Level: Thunder",
    powerRating: "Power: 93/100",
    accentColor: "#00D4FF",
    is_registration_open: true,
    coordinator_name: "Geo George",
    coordinator_phone: "+91 94471 44555",
    coordinator_email: "geo@macfast.org",
    rules: [
      "Individual entry (Shooter vs Official Festival Goalkeeper).",
      "Best of 5 penalties; sudden death if scores are tied.",
      "Decisions of referee on line violations are final.",
      "Football studs or turf shoes required."
    ]
  },

  // ─── SCHOOL EVENTS (9 EVENTS) ────────────────────────────────────
  {
    id: 15,
    title: "Peter Parker: Junior Code Web",
    slug: "peter-parker-junior-code-web",
    subtitle: "High School Junior Coding Challenge",
    description: "Young web slingers battle in visual and block programming, introductory Python logic, and algorithmic puzzles.",
    audience: "school",
    category: "technical",
    type: "solo",
    registration_fee: 50,
    prize_pool: 3000,
    difficulty: "medium",
    max_participants: 30,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "10:00:00",
    venue: "Junior Computing Lab",
    image: "/MARVEL/Spider-man.png",
    hero: "Spider-Man",
    level: "Level: Junior",
    powerRating: "Power: 88/100",
    accentColor: "#ED1D24",
    is_registration_open: true,
    coordinator_name: "Prof. Priya Nair",
    coordinator_phone: "+91 94471 55666",
    coordinator_email: "priya.school@macfast.org",
    rules: [
      "Open to high school students (Classes 8 through 12).",
      "Languages: Python, C, Java, or Scratch/Block Logic.",
      "Individual participation.",
      "Duration: 90 minutes."
    ]
  },
  {
    id: 16,
    title: "Stark Expo: School Innovation Hub",
    slug: "stark-expo-school-innovation-hub",
    subtitle: "Working Science & Tech Model Expo",
    description: "Showcase breakthrough STEM innovations, robotics prototypes, and green energy concepts before university professors.",
    audience: "school",
    category: "technical",
    type: "duo",
    registration_fee: 50,
    prize_pool: 4000,
    difficulty: "hard",
    max_participants: 20,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "10:00:00",
    venue: "Stark School Expo Exhibition Hall",
    image: "/MARVEL/4081455907815375.png",
    hero: "Iron Man",
    level: "Level: Innovator",
    powerRating: "Power: 92/100",
    accentColor: "#FFD700",
    is_registration_open: true,
    coordinator_name: "Dr. Anita Joseph",
    coordinator_phone: "+91 94471 66777",
    coordinator_email: "anita@macfast.org",
    rules: [
      "Team of 1 to 3 school delegates.",
      "Working model or science demonstration required.",
      "Power sockets provided. Hazardous chemicals or open fires strictly prohibited.",
      "Jury evaluation based on scientific merit, innovation, and demonstration."
    ]
  },
  {
    id: 17,
    title: "Falcon: High School Science Quiz",
    slug: "falcon-high-school-science-quiz",
    subtitle: "STEM & Tech Quiz",
    description: "Soar high in competitive science trivia covering physics, chemistry, space tech, and Marvel science lore.",
    audience: "school",
    category: "general",
    type: "duo",
    registration_fee: 50,
    prize_pool: 3000,
    difficulty: "medium",
    max_participants: 25,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "10:00:00",
    venue: "School Arena Auditorium",
    image: "/MARVEL/61080138757668761.png",
    hero: "Falcon",
    level: "Level: Skyward",
    powerRating: "Power: 89/100",
    accentColor: "#ED1D24",
    is_registration_open: true,
    coordinator_name: "Prof. Rajesh Kumar",
    coordinator_phone: "+91 94471 77888",
    coordinator_email: "rajesh.quiz@macfast.org",
    rules: [
      "Teams of 2 students from the same school.",
      "Preliminary written test followed by Top 5 live buzzer finals.",
      "Topics: General Science, Astronomy, Tech Discoveries, and Pop Culture Sci-Fi."
    ]
  },
  {
    id: 18,
    title: "Miles Morales: Comic Poster Art",
    slug: "miles-morales-comic-poster-art",
    subtitle: "Digital & Traditional Art Contest",
    description: "Unleash your artistic imagination and create stunning superhero posters, comic panels, or digital artwork on festival themes.",
    audience: "school",
    category: "general",
    type: "solo",
    registration_fee: 50,
    prize_pool: 2500,
    difficulty: "medium",
    max_participants: 30,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "10:00:00",
    venue: "Art Studio Gallery",
    image: "/MARVEL/The Spider….jpg",
    hero: "Miles Morales",
    level: "Level: Artist",
    powerRating: "Power: 90/100",
    accentColor: "#ED1D24",
    is_registration_open: true,
    coordinator_name: "Ananya Nair",
    coordinator_phone: "+91 94471 88999",
    coordinator_email: "ananya.art@macfast.org",
    rules: [
      "Individual participation.",
      "Drawing sheets provided; participants must bring their own colors/tablets.",
      "Theme announced at the start of the session.",
      "Duration: 2 hours."
    ]
  },
  {
    id: 19,
    title: "Ant-Man: Micro Web Craft",
    slug: "ant-man-micro-web-craft",
    subtitle: "Junior Web Page Design",
    description: "Design clean, responsive, and creative HTML/CSS web pages for a superhero gadget or portal.",
    audience: "school",
    category: "technical",
    type: "solo",
    registration_fee: 50,
    prize_pool: 2500,
    difficulty: "medium",
    max_participants: 25,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "10:00:00",
    venue: "MCA Lab 3",
    image: "/MARVEL/300685712645038155.png",
    hero: "Ant-Man",
    level: "Level: Quantum",
    powerRating: "Power: 87/100",
    accentColor: "#ED1D24",
    is_registration_open: true,
    coordinator_name: "Siddharth Menon",
    coordinator_phone: "+91 94471 99000",
    coordinator_email: "siddharth.web@macfast.org",
    rules: [
      "Pure HTML/CSS/JS web craft.",
      "Assets provided in a local folder.",
      "Evaluation based on visual aesthetics, mobile responsiveness, and clean code."
    ]
  },
  {
    id: 20,
    title: "Baby Groot: Eco Science Display",
    slug: "baby-groot-eco-science-display",
    subtitle: "Environmental Science Fair",
    description: "Present working solutions for sustainability, climate change, renewable energy, or organic recycling.",
    audience: "school",
    category: "general",
    type: "duo",
    registration_fee: 50,
    prize_pool: 3000,
    difficulty: "medium",
    max_participants: 20,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "10:00:00",
    venue: "Biosciences Courtyard",
    image: "/MARVEL/Doctor Strange.png",
    hero: "Baby Groot",
    level: "Level: Flora",
    powerRating: "Power: 88/100",
    accentColor: "#10B981",
    is_registration_open: true,
    coordinator_name: "Dr. Thomas Varghese",
    coordinator_phone: "+91 94472 00111",
    coordinator_email: "thomas.eco@macfast.org",
    rules: [
      "Teams of 2 students.",
      "Eco-friendly presentation materials strongly preferred.",
      "Interactive Q&A with judges on environmental impact."
    ]
  },
  {
    id: 21,
    title: "Captain Marvel: Speech & Debate",
    slug: "captain-marvel-speech-debate",
    subtitle: "High School English Extempore",
    description: "Step up to the podium and articulate compelling arguments on technology, future societies, and superhero ethics.",
    audience: "school",
    category: "general",
    type: "solo",
    registration_fee: 50,
    prize_pool: 3000,
    difficulty: "hard",
    max_participants: 25,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "10:00:00",
    venue: "Conference Hall B",
    image: "/MARVEL/658651514296997716.png",
    hero: "Captain Marvel",
    level: "Level: Cosmic",
    powerRating: "Power: 91/100",
    accentColor: "#FFD700",
    is_registration_open: true,
    coordinator_name: "Prof. Susan Kurian",
    coordinator_phone: "+91 94472 11222",
    coordinator_email: "susan.debate@macfast.org",
    rules: [
      "Extempore speech: 3 minutes preparation + 3 minutes speech.",
      "Topics selected by lot.",
      "Judged on eloquence, vocabulary, structure, and stage presence."
    ]
  },
  {
    id: 22,
    title: "Black Widow: School Mobile Arena",
    slug: "black-widow-school-mobile-arena",
    subtitle: "Junior Mobile Esports Clash",
    description: "High school squad and solo mobile gaming battles in Free Fire / BGMI junior friendly brackets.",
    audience: "school",
    category: "gaming",
    type: "squad",
    registration_fee: 50,
    prize_pool: 4000,
    difficulty: "hard",
    max_participants: 20,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "10:00:00",
    venue: "Junior Esports Zone",
    image: "/MARVEL/3025924746959430.jpg",
    hero: "Black Widow",
    level: "Level: Operative",
    powerRating: "Power: 92/100",
    accentColor: "#ED1D24",
    is_registration_open: true,
    coordinator_name: "Kiran Kumar",
    coordinator_phone: "+91 94472 22333",
    coordinator_email: "kiran.school@macfast.org",
    rules: [
      "High school squads (4 players).",
      "Strict anti-cheat protocols and room password sharing rules enforced.",
      "Points calculated via official match table."
    ]
  },
  {
    id: 23,
    title: "Deadpool: Meme Master Junior",
    slug: "deadpool-meme-master-junior",
    subtitle: "High School Meme & Humor Contest",
    description: "Craft hilarious, witty, and clever memes on school life, Marvel superheroes, and science concepts.",
    audience: "school",
    category: "general",
    type: "solo",
    registration_fee: 50,
    prize_pool: 3000,
    difficulty: "medium",
    max_participants: 30,
    participant_count: 0,
    event_date: "2026-09-24",
    event_time: "10:00:00",
    venue: "Creative Lab Alpha",
    image: "/MARVEL/Doctor Strange.png",
    hero: "Deadpool",
    level: "Level: Comic",
    powerRating: "Power: 90/100",
    accentColor: "#ED1D24",
    is_registration_open: true,
    coordinator_name: "Rahul E.",
    coordinator_phone: "+91 94472 33444",
    coordinator_email: "rahul.meme@macfast.org",
    rules: [
      "Individual entry.",
      "Templates provided or original edits allowed.",
      "Hate speech, profanity, or cyberbullying strictly prohibited.",
      "Judged on humor, virality potential, and relevance."
    ]
  }
];
