/* ===================================================================
   MACFIESTA 2K26 — OFFICIAL EVENTS & MISSIONS DIRECTORY
   13 College Events (₹1,06,000 Pool) + 8 School Events (₹28,000 Pool) + 1 STARK EXPO
   All rules, regulations, judging criteria, manpower, problems & solutions match official document.
   =================================================================== */

import { Event } from "@/types";

export interface FestivalEventItem extends Event {
  scope: "college" | "school";
  registrationFee: number;
  subtitle: string;
  hero: string;
  level: string;
  powerRating: string;
  accentColor: string;
  themeGradient: string;
  borderClass: string;
  glowClass: string;
  isCompetition?: boolean;
  manpower?: string[];
  possibleProblems?: { problem: string; solution: string }[];
  committeeApproach?: string;
  judgingRubric?: string;
  teamSizeText?: string;
}

export const ALL_EVENTS: FestivalEventItem[] = [
  // ─── COLLEGE EVENTS (13 OFFICIAL EVENTS) ──────────────────────────
  {
    _id: "clg-1",
    title: "Avengers: Code Assemble",
    slug: "vibe-coding-hackathon",
    subtitle: "Vibe Coding Hackathon",
    description: "Form your team, assemble your ideas, and engineer disruptive AI-infused software solutions to conquer the 6-hour hackathon arena.",
    scope: "college",
    category: "technical",
    type: "squad",
    registrationFee: 200,
    prizePool: 15000,
    difficulty: "expert",
    maxSeats: 35,
    registeredCount: 0,
    date: "25 Sep 2026",
    time: "10:00 AM – 04:00 PM",
    venue: "Stark Innovation Labs (Tech Zone)",
    coverImage: "/MARVEL/4081455907815375.png",
    hero: "Iron Man & Avengers",
    level: "Level: Alpha",
    powerRating: "Power: 99/100",
    accentColor: "#ED1D24",
    themeGradient: "from-marvel-red/30 to-metallic-gold/10",
    borderClass: "border-marvel-red/40 hover:border-marvel-red",
    glowClass: "hover:shadow-[0_0_40px_rgba(237,29,36,0.45)]",
    isLive: true,
    isCompetition: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Prof. Rajesh Kumar", phone: "+91 94470 11111", email: "rajesh@macfast.org" },
    teamSizeText: "1 or 3 members per team",
    rules: [
      "Team participation only; each team must have 1 or 3 members. A participant may belong to only one team.",
      "Teams must report at least 30 minutes before the start for verification, briefing, and workstation allocation.",
      "The problem statement/domain and final submission deadline will be announced by the organizers. The build period is 6 hours unless officially revised.",
      "All development must take place during the competition. Pre-built complete projects are prohibited; commonly available libraries, frameworks, APIs, and starter templates may be used if declared.",
      "Teams must use their own laptops, chargers, extension requirements, and any approved development hardware. Internet use is permitted only for documentation, packages, APIs, and research relevant to the build.",
      "The submission must include working source code, a short README, a presentation or pitch, and a functional demo or clearly documented prototype.",
      "Plagiarism, copied repositories presented as original work, unauthorized collaboration, or use of another team's code will result in disqualification.",
      "AI coding assistants may be used unless restricted during the briefing, but teams remain responsible for understanding, explaining, and validating every submitted component.",
      "Each team will receive a fixed presentation and question time. All members should be available during evaluation.",
      "Judging will consider problem relevance, innovation, technical implementation, usability, completeness, impact, and presentation. Judges' decision is final and binding."
    ],
    manpower: [
      "1 Event Head",
      "2 Technical Coordinators",
      "2–3 Mentors/Floor Volunteers",
      "2–3 Judges",
      "1 Timekeeper and Submission Coordinator"
    ],
    possibleProblems: [
      { problem: "Internet or power failure", solution: "Keep offline copies of problem statements and submission forms, arrange extension boards and backup power where possible, and record any official compensatory time equally for affected teams." },
      { problem: "Copied or pre-built projects", solution: "Collect repository links at the start and end, check commit history, question teams about implementation, and run plagiarism checks where practical." },
      { problem: "Submission failure", solution: "Provide one official upload route plus a local USB/offline backup. Record the submission time and freeze the submitted version." },
      { problem: "Unequal judging", solution: "Use a common scoring sheet and at least two judges. Resolve large scoring differences through a brief judges' review." },
      { problem: "System failure", solution: "Ask teams to maintain local backups. Organizers are not responsible for personal-device failure, but may allow a short verified recovery period if the schedule permits." }
    ],
    committeeApproach: "Begin with registration verification, rule briefing, and problem announcement. Record team details and repository links, conduct milestone checks without giving solutions, announce time warnings, freeze submissions at the deadline, and evaluate every team using the same rubric.",
    judgingRubric: "Innovation 20 | Technical Implementation 25 | Problem Relevance 15 | Functionality 15 | User Experience 10 | Impact/Scalability 5 | Presentation/Q&A 10"
  },
  {
    _id: "clg-2",
    title: "The Flash: Code Rush",
    slug: "coding-challenge",
    subtitle: "Coding Challenge",
    description: "Race against the clock in rapid algorithmic problem solving, syntax precision, and extreme speed coding.",
    scope: "college",
    category: "technical",
    type: "solo",
    registrationFee: 100,
    prizePool: 5000,
    difficulty: "hard",
    maxSeats: 50,
    registeredCount: 0,
    date: "25 Sep 2026",
    time: "10:00 AM – 12:00 PM",
    venue: "Turing Lab 2 (Tech Zone)",
    coverImage: "/MARVEL/61080138757668761.png",
    hero: "The Flash",
    level: "Level: Speedster",
    powerRating: "Power: 96/100",
    accentColor: "#FFD700",
    themeGradient: "from-metallic-gold/30 to-marvel-red/10",
    borderClass: "border-metallic-gold/40 hover:border-metallic-gold",
    glowClass: "hover:shadow-[0_0_40px_rgba(255,215,0,0.45)]",
    isLive: true,
    isCompetition: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Ananya Nair", phone: "+91 94470 22222", email: "ananya@macfast.org" },
    teamSizeText: "Individual participation only",
    rules: [
      "Individual participation only. Participants must use the registration name and assigned system or seat.",
      "The challenge will contain programming problems of varying difficulty and must be completed within the announced duration (suggested: 2 hours).",
      "Only the programming languages and online/offline judge platform announced by the organizers may be used.",
      "Communication, code sharing, and use of another person's solution are prohibited.",
      "Use of generative AI, messaging applications, external solution websites, personal code libraries, or unauthorized devices is prohibited unless explicitly allowed.",
      "Solutions must read input and produce output exactly as specified. Hard-coded outputs or attempts to interfere with the judge platform lead to disqualification.",
      "Ranking will be based on problems solved, test cases passed, and penalty time or submission attempts as configured by the platform.",
      "Any technical issue must be reported immediately; time adjustments will be granted only by the Event Head and applied fairly.",
      "In a tie, the participant with more fully solved problems, then lower penalty time, then earlier final accepted submission will rank higher.",
      "The organizers' and judges' decision is final and binding."
    ],
    manpower: [
      "1 Event Head",
      "2 Technical Coordinators",
      "2 Lab Volunteers/Invigilators",
      "1 Judge or Problem-Setting Team"
    ],
    possibleProblems: [
      { problem: "Platform or network failure", solution: "Keep an offline problem set and local submission backup; pause or extend the contest only through an official announcement." },
      { problem: "Cheating or code sharing", solution: "Seat participants adequately apart, monitor screens, restrict unauthorized sites, and compare suspiciously similar code." },
      { problem: "Incorrect test cases", solution: "Test every problem in advance and keep one technical judge available to validate genuine disputes." },
      { problem: "Language/compiler issue", solution: "Publish supported versions before the event and test each compiler on the contest machines." }
    ],
    committeeApproach: "Run a 10-minute briefing and sample submission before starting the timer. Display remaining time, maintain an incident log, lock submissions at the end, and export the final scoreboard. Do not reveal hidden test cases during the competition.",
    judgingRubric: "Problems Solved & Test Cases Passed | Execution Time & Penalties | Tie-Break: Earliest Accepted Submission"
  },
  {
    _id: "clg-3",
    title: "Infinity War",
    slug: "bgmi",
    subtitle: "BGMI Tournament",
    description: "One battleground. One survivor. Drop onto the custom room battleground with your squad and battle for supremacy.",
    scope: "college",
    category: "sports",
    type: "squad",
    registrationFee: 200,
    prizePool: 7000,
    difficulty: "expert",
    maxSeats: 35,
    registeredCount: 0,
    date: "25 Sep 2026",
    time: "10:00 AM – 01:00 PM",
    venue: "Arena Zone (Esports Hub)",
    coverImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop",
    hero: "Thanos & Avengers",
    level: "Level: Battleground",
    powerRating: "Power: 98/100",
    accentColor: "#7B2FBE",
    themeGradient: "from-vibranium-purple/30 to-blue-600/10",
    borderClass: "border-vibranium-purple/40 hover:border-vibranium-purple",
    glowClass: "hover:shadow-[0_0_40px_rgba(123,47,190,0.45)]",
    isLive: true,
    isCompetition: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Kiran Kumar", phone: "+91 94470 33333", email: "kiran@macfast.org" },
    teamSizeText: "Squad (Exactly 4 players · No substitutes)",
    rules: [
      "Squad participation only; each squad must have exactly 4 players. Substitutes are not permitted.",
      "All players must use their registered in-game name and player ID. Account changes after verification require organizer approval.",
      "Matches will be played in the BGMI custom room using the announced map, mode, perspective, server, and scoring system.",
      "Players must use their own mobile devices, earphones, chargers, and permitted network connection. Tablets, emulators, triggers, controllers, config files, GFX tools, scripts, hacks, or unauthorized third-party software are prohibited.",
      "Teaming with opponents, stream-sniping, ghosting, exploiting bugs, abusive communication, and sharing room credentials are prohibited.",
      "Players must join the room before the announced deadline. The match will not be restarted for an individual device, battery, call, or network problem after the official start.",
      "A restart may occur only for a verified server/custom-room failure affecting several teams and only before the defined restart threshold.",
      "Points will be awarded for placement and finishes according to the published table. Penalties or disqualification may be imposed for rule violations.",
      "Tie-break order: total wins/Chicken Dinners → total finish points → best placement in the latest match → total damage if verified statistics are available."
    ],
    manpower: [
      "1 Event Head/Tournament Admin",
      "2 Room and Score Coordinators",
      "2 Floor Volunteers",
      "1 Technical/Network Support Volunteer",
      "1 Observer or Fair-Play Official"
    ],
    possibleProblems: [
      { problem: "Network or server issue", solution: "Test the custom room and connectivity, announce restart conditions beforehand, and never restart only because one player disconnects." },
      { problem: "Wrong player or account", solution: "Verify player IDs before the first match and maintain a registered roster." },
      { problem: "Cheating allegation", solution: "Collect evidence, review observer footage or match statistics, and avoid deciding from verbal claims alone." },
      { problem: "Score dispute", solution: "Publish the scoring table before play and display a provisional scoreboard with a short dispute window." }
    ],
    committeeApproach: "Conduct device and roster verification, explain room secrecy and scoring, run matches on a fixed schedule, capture end-screen statistics, calculate scores in a locked master sheet, and publish provisional results before final confirmation.",
    judgingRubric: "Placement Points + Kill/Finish Multipliers as per official BGMI point matrix"
  },
  {
    _id: "clg-4",
    title: "Justice League: Ultimate XI",
    slug: "efootball",
    subtitle: "EFootball Tournament",
    description: "Assemble your ultimate squad, rule the virtual pitch, and dominate rival managers in competitive eFootball showdowns.",
    scope: "college",
    category: "sports",
    type: "solo",
    registrationFee: 100,
    prizePool: 7000,
    difficulty: "hard",
    maxSeats: 35,
    registeredCount: 0,
    date: "25 Sep 2026",
    time: "10:00 AM – 01:00 PM",
    venue: "Arena Zone (Console & Mobile Hub)",
    coverImage: "https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=800&auto=format&fit=crop",
    hero: "Justice League",
    level: "Level: League",
    powerRating: "Power: 95/100",
    accentColor: "#00D4FF",
    themeGradient: "from-arc-cyan/30 to-blue-600/10",
    borderClass: "border-arc-cyan/40 hover:border-arc-cyan",
    glowClass: "hover:shadow-[0_0_40px_rgba(0,212,255,0.45)]",
    isLive: true,
    isCompetition: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Abhijith R.", phone: "+91 94470 44444", email: "abhijith@macfast.org" },
    teamSizeText: "Individual participation only",
    rules: [
      "Individual participation only. The format may be knockout or group-plus-knockout depending on registrations and must be announced before the draw.",
      "Matches will use the organizer-approved console/mobile platform, game version, controls, difficulty, team settings, and match duration.",
      "Suggested settings: standard teams, normal condition/arrows, extra time and penalties enabled for knockout matches, and no custom-modified squads unless announced.",
      "Abusive language, distracting the opponent, physical interference, deliberate disconnection, or damaging equipment results in penalties or disqualification.",
      "If a verified technical failure occurs, the official will decide whether to resume with the existing score/time or replay the match.",
      "A draw in a knockout match will be decided by extra time and penalties under the announced settings.",
      "The event official's decision is final and binding."
    ],
    manpower: [
      "1 Event Head",
      "1 Fixture and Result Coordinator",
      "2 Match Volunteers/Referees",
      "1 Technical Support Volunteer"
    ],
    possibleProblems: [
      { problem: "Controller or device failure", solution: "Test equipment before each round and keep at least one verified backup controller/device." },
      { problem: "Fixture delay", solution: "Use numbered fixtures, call the next players early, and apply the late-reporting rule consistently." },
      { problem: "Intentional disconnection", solution: "Record the score and time; the official may award a forfeit or resume from an equivalent match state." },
      { problem: "Settings dispute", solution: "Display approved settings beside the match area and have both players confirm them before kickoff." }
    ],
    committeeApproach: "Publish the bracket and settings before Round 1. Record every result with both players' confirmation, prepare the next fixture while the current match is running, and keep spectators behind a defined boundary.",
    judgingRubric: "Head-to-head match score | Extra time & Penalties for knockout matches"
  },
  {
    _id: "clg-5",
    title: "Stark Industries: The Pitch",
    slug: "shark-tank",
    subtitle: "Shark Tank / Business Pitch",
    description: "Pitch bold, think bigger, and win big. Present groundbreaking startup ventures and enterprise solutions to seasoned venture evaluators.",
    scope: "college",
    category: "management",
    type: "duo",
    registrationFee: 150,
    prizePool: 15000,
    difficulty: "expert",
    maxSeats: 20,
    registeredCount: 0,
    date: "25 Sep 2026",
    time: "10:00 AM – 12:00 PM",
    venue: "MBA Executive Boardroom (Business Zone)",
    coverImage: "/MARVEL/300685712645038155.png",
    hero: "Tony Stark",
    level: "Level: Billionaire",
    powerRating: "Power: 98/100",
    accentColor: "#FFD700",
    themeGradient: "from-metallic-gold/30 to-marvel-red/10",
    borderClass: "border-metallic-gold/40 hover:border-metallic-gold",
    glowClass: "hover:shadow-[0_0_40px_rgba(255,215,0,0.45)]",
    isLive: true,
    isCompetition: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Prof. Priya Nair", phone: "+91 94470 55555", email: "priya@macfast.org" },
    teamSizeText: "Teams of 2 members",
    rules: [
      "Teams may consist of 2 members. Each participant may represent only one team.",
      "Teams must present an original business idea, startup concept, product, service, or social enterprise appropriate to the announced theme, if any.",
      "Each team will receive a fixed slot (suggested: 5 minutes for pitching and 3 minutes for judges' questions).",
      "The pitch should clearly cover the problem, proposed solution, target users, value proposition, market opportunity, competitors, revenue or sustainability model, feasibility, and next steps.",
      "A slide deck, prototype, mock-up, or demo may be used. All files must be submitted in the announced format before the deadline.",
      "Claims, statistics, financial projections, intellectual property, and endorsements must not be intentionally false or misleading. Sources should be identified when requested.",
      "Existing concepts may be improved, but copied pitch decks or direct imitation without meaningful original contribution may be disqualified.",
      "The order of presentation will be decided by draw or pre-published schedule. Late teams may be moved to the end or marked absent.",
      "Time-limit violations will attract a predefined penalty. Judges may stop a pitch after the grace period.",
      "Judging will consider problem clarity, innovation, market understanding, feasibility, business model, impact, presentation, and response to questions. Judges' decision is final."
    ],
    manpower: [
      "1 Event Head",
      "2–3 Judges",
      "1 Stage Moderator",
      "1 Timekeeper",
      "2 Technical/Registration Volunteers"
    ],
    possibleProblems: [
      { problem: "Presentation file failure", solution: "Collect decks early in PDF and PPTX formats and keep them on two devices." },
      { problem: "Pitch exceeds time", solution: "Show warning cards or signals at one minute remaining and at time-up; apply the same penalty to all teams." },
      { problem: "Unfair or aggressive questioning", solution: "The moderator should control Q&A and stop personal, discriminatory, or irrelevant questions." },
      { problem: "Copied idea dispute", solution: "Judge the originality of execution and require teams to disclose existing inspirations; avoid making legal ownership determinations during the event." }
    ],
    committeeApproach: "Use one scoring sheet for every judge. Average judges' scores and document any penalty.",
    judgingRubric: "Problem & Need 15 | Innovation 20 | Market/Users 15 | Business Model 15 | Feasibility 15 | Impact/Scalability 10 | Pitch/Q&A 10"
  },
  {
    _id: "clg-6",
    title: "Spider-Verse: Frame Hunt",
    slug: "photography",
    subtitle: "Photography Competition",
    description: "Capture the moment. Own the frame. Hunt for powerful visual narratives and untouched photographic captures across the festival.",
    scope: "college",
    category: "general",
    type: "solo",
    registrationFee: 100,
    prizePool: 5000,
    difficulty: "medium",
    maxSeats: 50,
    registeredCount: 0,
    date: "25 Sep 2026",
    time: "10:00 AM – 02:00 PM",
    venue: "Campus Wide Visual Spots (Creative Zone)",
    coverImage: "/MARVEL/Spider-man.png",
    hero: "Spider-Man",
    level: "Level: Shutter",
    powerRating: "Power: 94/100",
    accentColor: "#ED1D24",
    themeGradient: "from-marvel-red/30 to-blue-600/10",
    borderClass: "border-marvel-red/40 hover:border-marvel-red",
    glowClass: "hover:shadow-[0_0_40px_rgba(237,29,36,0.45)]",
    isLive: true,
    isCompetition: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Siddharth Menon", phone: "+91 94470 66666", email: "siddharth@macfast.org" },
    teamSizeText: "Individual participation only",
    rules: [
      "Individual participation only.",
      "The theme will be announced at the beginning of the competition.",
      "Each participant must submit exactly one photograph based on the announced theme.",
      "The photograph must be captured during the official competition period; previously captured photographs are strictly prohibited.",
      "Participants may use a mobile phone or digital camera.",
      "No editing, filters, enhancement, compositing, or post-processing is allowed. The original capture must be submitted.",
      "The original file and metadata must be retained and produced if requested.",
      "The photograph must be submitted through the official method before the deadline; late or multiple submissions may be rejected.",
      "Participants must remain within the permitted photography area and must not enter restricted or unsafe locations.",
      "Judging will consider relevance to theme, composition, creativity, lighting, storytelling, and technical quality. Judges' decision is final and binding."
    ],
    manpower: [
      "1 Event Head",
      "1 Judge or Judging Team",
      "2 Volunteers — Registration and Submission"
    ],
    possibleProblems: [
      { problem: "Old photographs", solution: "Check the original file and metadata where necessary and ask the participant to explain the location and capture process." },
      { problem: "Submission failure", solution: "Use a fixed folder/form and keep a USB or offline transfer backup." },
      { problem: "Participants leaving campus", solution: "Define the permitted area on a map and announce restricted zones before starting." },
      { problem: "Editing dispute", solution: "Accept only the original file and compare metadata or camera preview where required." },
      { problem: "Consent or privacy complaint", solution: "Remove the image from judging until the Event Head verifies consent and appropriateness." }
    ],
    committeeApproach: "Define the theme, time window, allowed area, file-naming format, and submission point in the opening briefing. Example: capture between 10:00 AM and 12:00 PM and submit one original image by 12:15 PM. Preserve originals until results are announced.",
    judgingRubric: "Relevance to Theme | Composition | Creativity | Lighting | Storytelling | Technical Quality"
  },
  {
    _id: "clg-7",
    title: "Deadpool: Reel Chaos",
    slug: "reels-competition",
    subtitle: "Reels Competition",
    description: "Create chaos. Go viral. Produce energetic, hilarious, and visually engaging short-form video reels that capture the spirit of MACFIESTA.",
    scope: "college",
    category: "general",
    type: "solo",
    registrationFee: 100,
    prizePool: 5000,
    difficulty: "medium",
    maxSeats: 30,
    registeredCount: 0,
    date: "25 Sep 2026",
    time: "10:00 AM – 02:00 PM",
    venue: "Media Studio / Campus (Talent Zone)",
    coverImage: "/MARVEL/The Spider….jpg",
    hero: "Deadpool",
    level: "Level: Maximum Effort",
    powerRating: "Power: 95/100",
    accentColor: "#ED1D24",
    themeGradient: "from-marvel-red/30 to-black/40",
    borderClass: "border-marvel-red/40 hover:border-marvel-red",
    glowClass: "hover:shadow-[0_0_40px_rgba(237,29,36,0.45)]",
    isLive: true,
    isCompetition: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Rohan Varghese", phone: "+91 94470 77777", email: "rohan@macfast.org" },
    teamSizeText: "Individual participation only",
    rules: [
      "Individual participation only.",
      "The theme will be announced at the start. The reel must be planned and recorded during the official competition period.",
      "The final reel must follow the announced duration (suggested: 30 to 60 seconds) and must be submitted before the deadline.",
      "Mobile editing applications may be used. Stock assets, templates, music, sound effects, and AI-generated elements must comply with the announced policy and should be disclosed when requested.",
      "Previously completed videos or substantially pre-edited reels are prohibited. Organizers may request raw clips or project files.",
      "Filming must remain within permitted areas and must not obstruct classes, traffic, emergency access, or other events.",
      "Participants must obtain consent before prominently featuring non-team members. Pranks, harassment, dangerous stunts, property damage, and unauthorized recording in private areas are prohibited.",
      "Content must not be obscene, hateful, discriminatory, defamatory, politically inflammatory, or damaging to the institution's reputation.",
      "Judging will consider theme relevance, originality, storytelling, editing, audio-visual quality, engagement, and overall impact. Judges' decision is final."
    ],
    manpower: [
      "1 Event Head",
      "1–2 Judges",
      "2 Submission/Area Volunteers",
      "1 Technical Coordinator"
    ],
    possibleProblems: [
      { problem: "Use of old footage", solution: "Request raw clips with timestamps or inspect project files where necessary." },
      { problem: "Copyrighted audio", solution: "Encourage royalty-free, licensed, or platform-cleared audio and ask teams to identify the track used." },
      { problem: "Unsafe or disruptive filming", solution: "Brief permitted areas and authorize volunteers to stop dangerous or disruptive activity immediately." },
      { problem: "Large-file upload failure", solution: "Set an MP4 format and resolution limit and provide local transfer/USB backup." },
      { problem: "Consent complaint", solution: "Require removal of disputed footage or disqualify the entry if consent and privacy rules were ignored." }
    ],
    committeeApproach: "Announce theme, duration, aspect ratio, file format, permitted areas, and AI/stock-media policy together. Give a final upload window, verify that each file plays correctly, and keep one unmodified master copy for judging.",
    judgingRubric: "Theme Relevance | Originality | Storytelling | Editing & Transitions | Audio-Visual Quality | Overall Impact"
  },
  {
    _id: "clg-8",
    title: "Guardians of the Galaxy: Dance Off",
    slug: "group-dance",
    subtitle: "Group Dance",
    description: "Own the beat. Rule the galaxy. Deliver an electrifying group dance performance with cosmic synchronization and powerhouse choreography.",
    scope: "college",
    category: "cultural",
    type: "group",
    registrationFee: 150,
    prizePool: 5000,
    difficulty: "hard",
    maxSeats: 16,
    registeredCount: 0,
    date: "25 Sep 2026",
    time: "10:00 AM – 12:00 PM",
    venue: "Main Stage Arena (Talent Zone)",
    coverImage: "https://images.unsplash.com/photo-1547153760-18fc86324498?q=80&w=800&auto=format&fit=crop",
    hero: "Star-Lord & Guardians",
    level: "Level: Cosmic",
    powerRating: "Power: 97/100",
    accentColor: "#7B2FBE",
    themeGradient: "from-vibranium-purple/30 to-arc-cyan/10",
    borderClass: "border-vibranium-purple/40 hover:border-vibranium-purple",
    glowClass: "hover:shadow-[0_0_40px_rgba(123,47,190,0.45)]",
    isLive: true,
    isCompetition: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Meera Nair", phone: "+91 94470 88888", email: "meera@macfast.org" },
    teamSizeText: "4 to 8 performers per team",
    rules: [
      "Each team must have 4 to 8 performers. Only registered members may perform.",
      "Performance duration should be 5 minutes including entry and exit. Exceeding the limit will attract a penalty.",
      "Music must be submitted before the announced deadline in MP3 format, with a backup copy carried by the team.",
      "Teams must report to the holding area at least 30 minutes before their slot. The performance order will be decided by draw or schedule.",
      "Lyrics, gestures, costumes, and themes must not be obscene, hateful, discriminatory, or targeted at individuals or communities.",
      "Fire, smoke, liquids, glass, sharp objects, explosives, confetti that creates a hazard, and other dangerous props are prohibited.",
      "Props must be declared in advance, be movable within the allotted transition time, and must not damage or dirty the stage.",
      "Teams are responsible for safe choreography. Dangerous lifts or acrobatics may be stopped by the Stage Manager.",
      "A music restart will be allowed only for a verified organizer-side technical failure and normally only once.",
      "Judging will consider choreography, synchronization, creativity, technique, expressions, costumes, stage use, energy, and overall impact. Judges' decision is final."
    ],
    manpower: [
      "1 Event Head",
      "2–3 Judges",
      "1 Stage Manager",
      "1 Sound/Technical Operator",
      "2 Backstage Volunteers",
      "1 Timekeeper"
    ],
    possibleProblems: [
      { problem: "Wrong or corrupted audio", solution: "Collect and test tracks in advance, rename files with team number, and keep a second device and team backup." },
      { problem: "Stage delay", solution: "Keep the next two teams ready and enforce prop setup/removal time." },
      { problem: "Unsafe move or injury", solution: "Inspect risky props, keep first aid accessible, and empower the Stage Manager to stop the act." },
      { problem: "Judging dispute", solution: "Use a common scoring rubric and prevent participants from approaching judges directly." }
    ],
    committeeApproach: "Conduct stage measurement and audio testing before the event.",
    judgingRubric: "Choreography 20 | Synchronization 20 | Creativity 15 | Technique 15 | Expressions/Stage Presence 15 | Costume/Theme 5 | Overall Impact 10"
  },
  {
    _id: "clg-9",
    title: "The Dark Knight: Hunt for the Signal",
    slug: "treasure-hunt",
    subtitle: "Treasure Hunt",
    description: "Follow the clues. Become the legend. Navigate secret campus checkpoints and decrypt cryptic signals to claim the ultimate bounty.",
    scope: "college",
    category: "general",
    type: "squad",
    registrationFee: 200,
    prizePool: 15000,
    difficulty: "expert",
    maxSeats: 40,
    registeredCount: 0,
    date: "25 Sep 2026",
    time: "10:00 AM – 01:00 PM",
    venue: "Campus Perimeter (Adventure / Mystery Zone)",
    coverImage: "/MARVEL/3025924746959430.jpg",
    hero: "The Dark Knight",
    level: "Level: Detective",
    powerRating: "Power: 100/100",
    accentColor: "#FFD700",
    themeGradient: "from-metallic-gold/30 to-black/50",
    borderClass: "border-metallic-gold/40 hover:border-metallic-gold",
    glowClass: "hover:shadow-[0_0_40px_rgba(255,215,0,0.45)]",
    isLive: true,
    isCompetition: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Saji George", phone: "+91 94470 99999", email: "saji@macfast.org" },
    teamSizeText: "Teams of 4 members",
    rules: [
      "Teams must consist of 4 members. Team membership cannot change after the hunt begins.",
      "All teams will receive the first clue at the official start. Clues must be solved in the prescribed order unless stated otherwise.",
      "Teams must remain within the marked campus boundaries and must not enter classrooms, offices, laboratories, rooftops, construction zones, roads, or other restricted areas unless a clue explicitly permits access.",
      "Running in unsafe areas, climbing, forcing locks, moving institutional property, damaging clues, and disturbing other events are prohibited.",
      "Teams may not share clues, answers, locations, photographs, or passwords with another team or interfere with another team's progress.",
      "Use of phones, internet, maps, calls, or external help will follow the policy announced at briefing. Unauthorized outside assistance is prohibited.",
      "Every checkpoint must be validated by the assigned volunteer before the next clue is issued.",
      "A missing or damaged clue must be reported immediately; teams must not create, relocate, or conceal clues.",
      "The winner is the first eligible team to complete all checkpoints and the final task correctly. Time penalties apply for hints or violations as announced."
    ],
    manpower: [
      "1 Event Head",
      "1 Control-Room Coordinator",
      "1 Volunteer per Active Checkpoint",
      "2 Route/Safety Marshals",
      "1 Time and Result Recorder"
    ],
    possibleProblems: [
      { problem: "Clue is lost or moved", solution: "Keep duplicate sealed clue sets and station volunteers at sensitive checkpoints." },
      { problem: "Teams follow one another", solution: "Use staggered starts, alternate clue orders, or parallel routes where possible." },
      { problem: "Unsafe access", solution: "Physically mark restricted zones and place marshals at high-risk junctions." },
      { problem: "Answer dispute", solution: "Maintain an official answer key and checkpoint log with timestamps." },
      { problem: "External help", solution: "State the phone policy clearly and monitor checkpoints; apply the published penalty consistently." }
    ],
    committeeApproach: "Test every route and clue before the event, calculate safe walking time, prepare duplicate clue packets, brief checkpoint volunteers with accepted answers, and run all communication through one control room.",
    judgingRubric: "First eligible team to complete all checkpoints and final task correctly (adjusted for time penalties)"
  },
  {
    _id: "clg-10",
    title: "Batman: Gotham Files",
    slug: "cold-investigation",
    subtitle: "Cold Investigation",
    description: "Every clue lies. Find the truth. Analyze forensics, interrogate roleplay witnesses, and solve the complex cold investigation case.",
    scope: "college",
    category: "general",
    type: "squad",
    registrationFee: 150,
    prizePool: 7000,
    difficulty: "hard",
    maxSeats: 40,
    registeredCount: 0,
    date: "25 Sep 2026",
    time: "10:00 AM – 02:00 PM",
    venue: "Room 204 (Adventure / Mystery Zone)",
    coverImage: "/MARVEL/peakpx.png",
    hero: "Detective Batman",
    level: "Level: Forensic",
    powerRating: "Power: 96/100",
    accentColor: "#00D4FF",
    themeGradient: "from-arc-cyan/30 to-black/40",
    borderClass: "border-arc-cyan/40 hover:border-arc-cyan",
    glowClass: "hover:shadow-[0_0_40px_rgba(0,212,255,0.45)]",
    isLive: true,
    isCompetition: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Arun Kurian", phone: "+91 94471 00001", email: "arun@macfast.org" },
    teamSizeText: "Teams of 2 to 4 members",
    rules: [
      "Teams must consist of 2 to 4 members. Only registered members may discuss or submit the solution.",
      "Each team will receive the same case file, evidence set, witness statements, and task instructions at the start.",
      "Teams must analyze only the provided evidence. Internet searches, outside help, photographing another team's materials, and exchanging information are prohibited unless a research phase is explicitly announced.",
      "Evidence packets must not be marked, altered, removed, or shared. Any physical evidence must remain at its assigned station.",
      "Teams may question role-play witnesses only during assigned slots and only through respectful, case-related questions.",
      "The final submission must identify the conclusion/suspect, timeline or reasoning, key evidence, and answers to all required questions.",
      "Unsupported accusations, offensive profiling, or conclusions based on caste, religion, gender, disability, appearance, or other protected traits will not be accepted.",
      "Hints, if offered, will carry a published time or score penalty.",
      "Submission after the deadline may receive a penalty or be rejected. Once submitted, answers cannot be altered.",
      "Judging will consider correctness, evidence use, logical reasoning, completeness, and clarity. Judges' decision is final."
    ],
    manpower: [
      "1 Event Head",
      "1 Case Master/Judge",
      "2 Evidence or Witness Volunteers",
      "1 Timekeeper",
      "1 Submission Coordinator"
    ],
    possibleProblems: [
      { problem: "Case ambiguity", solution: "Pilot-test the case with non-participants and prepare an authoritative solution and accepted reasoning paths." },
      { problem: "Evidence leakage", solution: "Use numbered sealed packets, collect every packet, and keep witnesses isolated from waiting teams." },
      { problem: "Teams overhear others", solution: "Separate work areas and schedule witness questioning privately." },
      { problem: "Scoring dispute", solution: "Score against an evidence-based answer key, award partial marks using written criteria, and retain submissions." }
    ],
    committeeApproach: "Issue identical sealed files, record opening time, control witness access, announce time warnings, and collect a signed final answer sheet.",
    judgingRubric: "Correct Conclusion 25 | Evidence Identification 25 | Logical Reconstruction 25 | Completeness 15 | Presentation 10"
  },
  {
    _id: "clg-11",
    title: "Doctor Strange: Multiverse Escape",
    slug: "escape-room",
    subtitle: "Escape Room",
    description: "One room. Infinite realities. Escape. Solve dimensional puzzles and mystic riddles before the timeline portal shuts down.",
    scope: "college",
    category: "general",
    type: "squad",
    registrationFee: 200,
    prizePool: 5000,
    difficulty: "hard",
    maxSeats: 30,
    registeredCount: 0,
    date: "25 Sep 2026",
    time: "10:00 AM – 01:00 PM",
    venue: "Mystic Chamber (Adventure / Mystery Zone)",
    coverImage: "/MARVEL/Doctor Strange.png",
    hero: "Doctor Strange",
    level: "Level: Mystic",
    powerRating: "Power: 98/100",
    accentColor: "#FF8C00",
    themeGradient: "from-amber-600/30 to-vibranium-purple/15",
    borderClass: "border-amber-500/40 hover:border-amber-500",
    glowClass: "hover:shadow-[0_0_40px_rgba(255,140,0,0.45)]",
    isLive: true,
    isCompetition: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Dr. Thomas Varghese", phone: "+91 94471 00002", email: "thomas@macfast.org" },
    teamSizeText: "Teams of 2 to 4 members",
    rules: [
      "Teams must consist of 2 to 4 members. Only one team may enter a room/session at a time unless parallel identical rooms are used.",
      "Teams must complete the puzzles and final objective within the announced time limit.",
      "Participants may handle only items identified as part of the game. Locked, taped, labelled 'Do Not Touch,' electrical, ceiling, faculty, and emergency equipment must not be disturbed.",
      "No force is required. Breaking, bending, climbing, unscrewing, disconnecting, or damaging any object is prohibited.",
      "Phones, smart watches, internet access, outside communication, tools, and photography are prohibited inside unless specifically included in the game.",
      "Teams must not reveal puzzles, codes, solutions, room layout, or photographs to waiting participants.",
      "Hints may be requested through the official method and will carry the published time or score penalty.",
      "A safety instruction or stop command from the Room Master must be followed immediately. Participants may leave at any time in an emergency.",
      "The winning team will be determined by successful completion, then lowest adjusted time after hint/penalty additions.",
      "Any damaged or missing component must be reported immediately. Officials' decision is final."
    ],
    manpower: [
      "1 Event Head",
      "1 Room Master per Room",
      "1 Reset/Puzzle Volunteer per Room",
      "1 Queue and Time Coordinator",
      "1 Safety Volunteer"
    ],
    possibleProblems: [
      { problem: "Puzzle component missing or reset incorrectly", solution: "Use a reset checklist and photograph the correct starting state before every session." },
      { problem: "Participant panic or injury", solution: "Keep exits unlocked, explain the emergency signal, monitor continuously, and maintain clear walkways." },
      { problem: "Solution leakage", solution: "Collect phones or seal them, separate completed and waiting teams, and require confidentiality until all sessions finish." },
      { problem: "Equipment failure", solution: "Prepare duplicate locks, clues, batteries, and manual override codes." },
      { problem: "Disputed completion time", solution: "Use one official timer and maintain a session log signed by the Room Master." }
    ],
    committeeApproach: "Run multiple full test sessions before the event. Brief teams on safety and prohibited areas, start the official timer only after the door briefing, record every hint, stop immediately on completion, and reset using a checklist before admitting the next team.",
    judgingRubric: "Successful completion status | Lowest adjusted time after hint and penalty calculation"
  },
  {
    _id: "clg-12",
    title: "Iron Chef: Battle of Heroes",
    slug: "master-cook",
    subtitle: "Master Cook",
    description: "Enter hungry. Leave legendary. Prove your culinary prowess across secret multi-round ingredient challenges.",
    scope: "college",
    category: "general",
    type: "solo",
    registrationFee: 200,
    prizePool: 5000,
    difficulty: "medium",
    maxSeats: 25,
    registeredCount: 0,
    date: "25 Sep 2026",
    time: "10:00 AM – 01:00 PM",
    venue: "Campus Culinary Pavilion (Creative Zone)",
    coverImage: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?q=80&w=800&auto=format&fit=crop",
    hero: "Iron Chef",
    level: "Level: Gourmet",
    powerRating: "Power: 93/100",
    accentColor: "#ED1D24",
    themeGradient: "from-marvel-red/30 to-metallic-gold/10",
    borderClass: "border-marvel-red/40 hover:border-marvel-red",
    glowClass: "hover:shadow-[0_0_40px_rgba(237,29,36,0.45)]",
    isLive: true,
    isCompetition: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Susan Philip", phone: "+91 94471 00003", email: "susan@macfast.org" },
    teamSizeText: "Individual participation only",
    rules: [
      "Individual participation only. Each participant must prepare and present their own dish or task.",
      "The competition will be conducted in multiple rounds. Each round will have a different cooking challenge or task, and the details will be disclosed only at the beginning of that round. The college will provide the ingredients required for each round.",
      "Participants must bring their own pans, vessels, knives, cutting boards, spoons, mixing bowls, and any other necessary cooking utensils or equipment. All preparation, cooking, plating, and workstation cleaning must be completed within the time announced for each round.",
      "Participants must disclose major allergens in every dish and must not use spoiled, unsafe, prohibited, or unlabeled ingredients.",
      "Hands, utensils, cutting boards, and work surfaces must be kept clean. Raw and ready-to-eat foods must be separated to prevent cross-contamination.",
      "Pre-cooked, pre-prepared, or partially prepared food must not be brought. Only safe and approved cooking equipment may be used. Open flames and high-risk equipment are prohibited unless specifically arranged and supervised.",
      "Appropriate clothing, tied hair, closed footwear, and safe knife handling are mandatory. Running and horseplay are prohibited.",
      "Each participant must complete and present the required dish or task before the time for that round expires. Qualification or elimination for subsequent rounds will follow the format announced by the organizers.",
      "Judges may refuse to taste food that appears unsafe, undercooked, contaminated, or allergen-unclear.",
      "Judging will consider taste, creativity, presentation, hygiene, proper use of the provided ingredients, and overall performance. Judges' decision is final."
    ],
    manpower: [
      "1 Event Head",
      "2–3 Food Judges",
      "1 Food-Safety/Faculty Supervisor",
      "2 Workstation Volunteers",
      "1 Timekeeper",
      "1 Electrical/Fire-Safety Support Person"
    ],
    possibleProblems: [
      { problem: "Allergy or food-safety risk", solution: "Collect ingredient/allergen declarations, keep first aid and emergency contacts available, and prohibit tasting of unsafe dishes." },
      { problem: "Electrical overload", solution: "Pre-calculate appliance load, assign sockets, avoid personal extension boards, and keep a suitable extinguisher nearby." },
      { problem: "Ingredient dispute", solution: "Ensure the same college-provided ingredients are distributed fairly to participants for each round." },
      { problem: "Equipment issue", solution: "Clearly state that participants must bring their own pans, vessels, utensils, and other required cooking equipment." },
      { problem: "Waste and cleaning", solution: "Provide labeled waste bins and require workstation clearance before the participant leaves." }
    ],
    committeeApproach: "Distribute the college-provided ingredients equally for each round, inspect participant-brought equipment at reporting, brief hygiene and emergency rules, allocate equal workstations, announce each round challenge at the start of that round, give time warnings, and record qualification or elimination before proceeding to the next round.",
    judgingRubric: "Taste | Creativity & Innovation | Presentation & Plating | Hygiene & Workstation Cleanliness | Proper use of provided ingredients"
  },
  {
    _id: "clg-13",
    title: "LexCorp vs Stark Industries",
    slug: "ultimate-marketing-challenge",
    subtitle: "The Ultimate Marketing Challenge",
    description: "Think. Persuade. Dominate. Wage high-stakes brand battles, advertising stunts, and strategic marketing campaigns.",
    scope: "college",
    category: "management",
    type: "squad",
    registrationFee: 150,
    prizePool: 10000,
    difficulty: "expert",
    maxSeats: 25,
    registeredCount: 0,
    date: "25 Sep 2026",
    time: "10:00 AM – 01:00 PM",
    venue: "Seminar Hall A (Business Zone)",
    coverImage: "/MARVEL/658651514296997716.png",
    hero: "Lex Luthor vs Tony Stark",
    level: "Level: Conglomerate",
    powerRating: "Power: 99/100",
    accentColor: "#10B981",
    themeGradient: "from-emerald-500/30 to-metallic-gold/10",
    borderClass: "border-emerald-500/40 hover:border-emerald-500",
    glowClass: "hover:shadow-[0_0_40px_rgba(16,185,129,0.45)]",
    isLive: true,
    isCompetition: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Prof. Ligo Koshy", phone: "+91 94471 00005", email: "ligo@macfast.org" },
    teamSizeText: "Teams of 2 to 4 members",
    rules: [
      "Teams must consist of 2 to 4 members. Each participant may represent only one team.",
      "The event may contain multiple rounds. Round details will be announced before each stage.",
      "Teams must work only within the announced preparation time and use only approved materials, devices, research sources, and AI tools.",
      "All campaign ideas, slogans, visuals, and pitches created for the competition must be substantially original. Existing brands may be referenced only as required by the task.",
      "Content must not be obscene, deceptive, defamatory, discriminatory, politically inflammatory, or harmful to individuals, communities, competitors, or the institution.",
      "If a surprise product or case is assigned, teams may not exchange products, briefs, confidential prompts, or answers with other teams.",
      "Every member should contribute; however, the team may nominate presenters for individual rounds.",
      "Presentations must remain within the fixed time. Late submission or exceeding presentation time will attract the announced penalty.",
      "Judges may ask questions about target audience, insight, positioning, channel choice, budget, ethics, feasibility, and measurement.",
      "Elimination and tie-break rules will be announced before the event. Judges' decision is final and binding."
    ],
    manpower: [
      "1 Event Head",
      "2–3 Marketing/Business Judges",
      "1 Round Moderator",
      "1 Timekeeper and Score Coordinator",
      "2 Material/Technical Volunteers"
    ],
    possibleProblems: [
      { problem: "Copied campaign", solution: "Request working notes, check obvious copied slogans/assets, and score originality of strategy and execution." },
      { problem: "Unclear round instructions", solution: "Prepare written briefs with deliverables, time, permitted tools, and scoring criteria; read the same clarification to every team." },
      { problem: "Biased evaluation", solution: "Use at least two judges and a standard score sheet for each round." },
      { problem: "Presentation failure", solution: "Collect files before the pitch and accept a PDF backup." },
      { problem: "Offensive or misleading campaign", solution: "The moderator may stop the presentation and refer it to the Event Head for penalty or disqualification." }
    ],
    committeeApproach: "Publish the round structure and elimination method before starting. Preserve score sheets until results are final.",
    judgingRubric: "Consumer Insight 15 | Creativity 20 | Strategy/Positioning 20 | Feasibility 15 | Communication 15 | Ethics 5 | Presentation/Q&A 10"
  },

  // ─── SCHOOL EVENTS (8 COMPETITIONS + 1 STARK EXPO) ──────────────
  {
    _id: "sch-1",
    title: "Multiverse: Imagine It",
    slug: "school-ai-image-creation",
    subtitle: "AI Prompt – Image Creation",
    description: "School Day tech challenge — craft generative prompts to synthesize superhero and sci-fi scenes.",
    scope: "school",
    category: "technical",
    type: "solo",
    registrationFee: 0,
    prizePool: 3000,
    difficulty: "medium",
    maxSeats: 30,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM – 12:00 PM",
    venue: "AI Innovation Lab 1 (Open Event)",
    coverImage: "/MARVEL/In a city that never sleeps, I find my….png",
    hero: "Vision & Multiverse",
    level: "Level: Prompt Master",
    powerRating: "Power: 95/100",
    accentColor: "#00D4FF",
    themeGradient: "from-arc-cyan/30 to-vibranium-purple/10",
    borderClass: "border-arc-cyan/40 hover:border-arc-cyan",
    glowClass: "hover:shadow-[0_0_40px_rgba(0,212,255,0.45)]",
    isLive: true,
    isCompetition: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Ashwin Kumar", phone: "+91 94471 10001", email: "ashwin@macfast.org" },
    teamSizeText: "Individual participation",
    rules: [
      "Open to high school and plus-two students with valid school ID card.",
      "Prompt crafting and image generation must take place during the allotted session.",
      "Participants will be evaluated on creativity, prompt specificity, aesthetic composition, and theme relevance.",
      "Decision of the judges is final."
    ]
  },
  {
    _id: "sch-2",
    title: "SpiderLens: Freeze the Moment",
    slug: "school-photography",
    subtitle: "Photography Competition",
    description: "School Day photography challenge — capture candid moments, festival energy, and vivid stories.",
    scope: "school",
    category: "general",
    type: "solo",
    registrationFee: 0,
    prizePool: 3000,
    difficulty: "easy",
    maxSeats: 30,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM – 01:00 PM",
    venue: "Campus Trail (Open Event)",
    coverImage: "/MARVEL/Spider-man.png",
    hero: "Peter Parker SpiderLens",
    level: "Level: Junior Shutter",
    powerRating: "Power: 92/100",
    accentColor: "#ED1D24",
    themeGradient: "from-marvel-red/30 to-arc-cyan/10",
    borderClass: "border-marvel-red/40 hover:border-marvel-red",
    glowClass: "hover:shadow-[0_0_40px_rgba(237,29,36,0.45)]",
    isLive: true,
    isCompetition: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Aria Sebastian", phone: "+91 94471 10002", email: "aria@macfast.org" },
    teamSizeText: "Individual participation",
    rules: [
      "Individual participation for school students.",
      "Photographs must be captured on MACFAST campus during the contest period.",
      "Unedited, original captures must be submitted before the deadline.",
      "Judged on theme relevance, framing, storytelling, and lighting."
    ]
  },
  {
    _id: "sch-3",
    title: "HeroVerse Dance-Off",
    slug: "school-spot-dance",
    subtitle: "Spot Dance Challenge",
    description: "School Day spot dance competition — step into the spotlight and groove when the beats drop.",
    scope: "school",
    category: "cultural",
    type: "solo",
    registrationFee: 0,
    prizePool: 5000,
    difficulty: "medium",
    maxSeats: 30,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM – 12:00 PM",
    venue: "Open Air Arena (Major Attraction)",
    coverImage: "https://images.unsplash.com/photo-1547153760-18fc86324498?q=80&w=800&auto=format&fit=crop",
    hero: "HeroVerse",
    level: "Level: Spot Rhythm",
    powerRating: "Power: 96/100",
    accentColor: "#7B2FBE",
    themeGradient: "from-vibranium-purple/30 to-marvel-red/10",
    borderClass: "border-vibranium-purple/40 hover:border-vibranium-purple",
    glowClass: "hover:shadow-[0_0_40px_rgba(123,47,190,0.45)]",
    isLive: true,
    isCompetition: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Suresh Pillai", phone: "+91 94471 10003", email: "suresh@macfast.org" },
    teamSizeText: "Individual participation",
    rules: [
      "Spot dance format on random audio tracks selected by the organizers.",
      "Judged on spontaneity, musicality, expression, rhythm, and stage presence.",
      "Vulgar gestures, dangerous stunts, and inappropriate costumes are prohibited."
    ]
  },
  {
    _id: "sch-4",
    title: "The Endgame Heist: Hunt for the Stones",
    slug: "school-treasure-hunt",
    subtitle: "Treasure Hunt",
    description: "School Day major attraction — solve riddles, explore safe campus zones, and retrieve the Infinity Stones.",
    scope: "school",
    category: "general",
    type: "squad",
    registrationFee: 0,
    prizePool: 5000,
    difficulty: "medium",
    maxSeats: 30,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM – 01:00 PM",
    venue: "Campus Grounds (Major Attraction)",
    coverImage: "/MARVEL/658651514296997716.png",
    hero: "Infinity Gauntlet",
    level: "Level: Gauntlet Quest",
    powerRating: "Power: 97/100",
    accentColor: "#FFD700",
    themeGradient: "from-metallic-gold/30 to-arc-cyan/10",
    borderClass: "border-metallic-gold/40 hover:border-metallic-gold",
    glowClass: "hover:shadow-[0_0_40px_rgba(255,215,0,0.45)]",
    isLive: true,
    isCompetition: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Prof. Saji George", phone: "+91 94471 10004", email: "saji@macfast.org" },
    teamSizeText: "Teams of 3 to 4 school students",
    rules: [
      "Team participation of 3 to 4 students from the same school.",
      "Solve clues in sequence; restricted campus areas must not be entered.",
      "First team to correctly validate all checkpoint stones wins."
    ]
  },
  {
    _id: "sch-5",
    title: "Groot's Green Mission",
    slug: "school-best-out-of-waste",
    subtitle: "Best Out of Waste",
    description: "School Day creative challenge — transform recyclables and scrap into functional or artistic eco-innovations.",
    scope: "school",
    category: "general",
    type: "duo",
    registrationFee: 0,
    prizePool: 3000,
    difficulty: "easy",
    maxSeats: 25,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM – 01:00 PM",
    venue: "Ecology Hall (Creative)",
    coverImage: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?q=80&w=800&auto=format&fit=crop",
    hero: "Groot",
    level: "Level: Eco Marvel",
    powerRating: "Power: 91/100",
    accentColor: "#10B981",
    themeGradient: "from-emerald-500/30 to-metallic-gold/10",
    borderClass: "border-emerald-500/40 hover:border-emerald-500",
    glowClass: "hover:shadow-[0_0_40px_rgba(16,185,129,0.45)]",
    isLive: true,
    isCompetition: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Anita Joseph", phone: "+91 94471 10005", email: "anita@macfast.org" },
    teamSizeText: "Teams of 2 students",
    rules: [
      "Teams of 2 students representing their school.",
      "Only waste and recyclable materials must be used.",
      "Judged on eco-innovation, artistic design, practicality, and presentation."
    ]
  },
  {
    _id: "sch-6",
    title: "Gotham: Mystery Files",
    slug: "school-mystery-case",
    subtitle: "Mystery Case / Detective Challenge",
    description: "School Day detective challenge — decipher clues, test logic, and crack the mystery case.",
    scope: "school",
    category: "general",
    type: "duo",
    registrationFee: 0,
    prizePool: 3000,
    difficulty: "medium",
    maxSeats: 30,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM – 01:00 PM",
    venue: "Room 102 (Fun / Problem-Solving)",
    coverImage: "/MARVEL/peakpx.png",
    hero: "Robin & Detective",
    level: "Level: Sleuth",
    powerRating: "Power: 93/100",
    accentColor: "#00D4FF",
    themeGradient: "from-arc-cyan/30 to-black/40",
    borderClass: "border-arc-cyan/40 hover:border-arc-cyan",
    glowClass: "hover:shadow-[0_0_40px_rgba(0,212,255,0.45)]",
    isLive: true,
    isCompetition: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Anjali Mathew", phone: "+91 94471 10006", email: "anjali@macfast.org" },
    teamSizeText: "Teams of 2 students",
    rules: [
      "Teams of 2 students.",
      "Case file will be issued at the start; solve using only provided clues.",
      "Evaluated on correct deduction, timeline accuracy, and reasoning."
    ]
  },
  {
    _id: "sch-7",
    title: "Justice League: Mini Clash",
    slug: "school-3v3-football",
    subtitle: "3v3 Football",
    description: "School Day 3v3 mini turf football — dynamic teamwork, electric agility, and tournament glory.",
    scope: "school",
    category: "sports",
    type: "squad",
    registrationFee: 0,
    prizePool: 3000,
    difficulty: "medium",
    maxSeats: 20,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM – 01:00 PM",
    venue: "Junior Turf (Major Attraction)",
    coverImage: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?q=80&w=800&auto=format&fit=crop",
    hero: "Justice League Youth",
    level: "Level: Prodigy",
    powerRating: "Power: 94/100",
    accentColor: "#00D4FF",
    themeGradient: "from-arc-cyan/30 to-blue-600/10",
    borderClass: "border-arc-cyan/40 hover:border-arc-cyan",
    glowClass: "hover:shadow-[0_0_40px_rgba(0,212,255,0.45)]",
    isLive: true,
    isCompetition: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Kiran Kumar", phone: "+91 94471 10007", email: "kiran@macfast.org" },
    teamSizeText: "3 players + 1 substitute",
    rules: [
      "3 players on field + 1 rolling substitute per team.",
      "Fast-paced knockout format with standard mini-football rules.",
      "Proper sports attire and turf shoes mandatory."
    ]
  },
  {
    _id: "sch-8",
    title: "Civil War: The Great Ideology Debate",
    slug: "school-debate-extempore",
    subtitle: "Debate / Extempore",
    description: "School Day debate and extempore — take the stage and defend ideas with conviction and eloquence.",
    scope: "school",
    category: "general",
    type: "solo",
    registrationFee: 0,
    prizePool: 3000,
    difficulty: "medium",
    maxSeats: 25,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM – 12:00 PM",
    venue: "Senate Hall B (Supporting Event)",
    coverImage: "/MARVEL/Doctor Strange.png",
    hero: "Professor X & Council",
    level: "Level: Orator",
    powerRating: "Power: 95/100",
    accentColor: "#FFD700",
    themeGradient: "from-metallic-gold/30 to-marvel-red/10",
    borderClass: "border-metallic-gold/40 hover:border-metallic-gold",
    glowClass: "hover:shadow-[0_0_40px_rgba(255,215,0,0.45)]",
    isLive: true,
    isCompetition: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Prof. Varghese Abraham", phone: "+91 94471 10008", email: "varghese@macfast.org" },
    teamSizeText: "Individual participation",
    rules: [
      "Individual participation for school students.",
      "Topics given on the spot with structured preparation time.",
      "Judged on eloquence, logical arguments, articulation, and rebuttal clarity."
    ]
  },
  {
    _id: "sch-9",
    title: "STARK EXPO",
    slug: "school-stark-expo",
    subtitle: "One Expo. Infinite Worlds of Discovery.",
    description: "Premier School Exhibition & Showcase across Artificial Intelligence (AI), Internet of Things (IoT), Science & Experiments, Biology & Life Sciences, and Psychology & Human Behaviour.",
    scope: "school",
    category: "technical",
    type: "group",
    registrationFee: 0,
    prizePool: null,
    difficulty: "expert",
    maxSeats: 50,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM – 04:00 PM",
    venue: "Stark Exhibition Pavilions (Exhibition / Expo)",
    coverImage: "/MARVEL/4081455907815375.png",
    hero: "Stark Expo Innovations",
    level: "Level: Grand Showcase",
    powerRating: "Power: 100/100",
    accentColor: "#00D4FF",
    themeGradient: "from-arc-cyan/30 to-metallic-gold/15",
    borderClass: "border-arc-cyan/40 hover:border-arc-cyan",
    glowClass: "hover:shadow-[0_0_40px_rgba(0,212,255,0.45)]",
    isLive: true,
    isCompetition: false,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Dr. Cherian P. George", phone: "+91 94471 10009", email: "cherian@macfast.org" },
    teamSizeText: "School Exhibition Teams (2 to 4 members)",
    rules: [
      "Open to school project teams showcasing science and technology models.",
      "Themes: Artificial Intelligence, Internet of Things, Science Experiments, Biology & Life Sciences, and Psychology.",
      "Non-competitive featured expo open for all visitors and students throughout Day 1."
    ]
  }
];

export const EVENTS_BY_SLUG: Record<string, FestivalEventItem> = ALL_EVENTS.reduce((acc, curr) => {
  acc[curr.slug] = curr;
  return acc;
}, {} as Record<string, FestivalEventItem>);
