/* ===================================================================
   MACFIESTA 2K26 — OFFICIAL EVENTS & MISSIONS DIRECTORY
   14 College Events (₹1,15,000 Pool) + 9 School Events (₹28,000+ Pool)
   =================================================================== */

import { Event } from "@/types";

export interface FestivalEventItem extends Event {
  scope: "college" | "school";
  registrationFee: number;
  subtitle: string;
  hero: string;
  level: string;
  powerRating: string;
  accentColor: string;
  themeGradient: string;
  borderClass: string;
  glowClass: string;
}

export const ALL_EVENTS: FestivalEventItem[] = [
  // ─── COLLEGE EVENTS (14 EVENTS) ──────────────────────────────────
  {
    _id: "clg-1",
    title: "Avengers: Code Assemble",
    slug: "avengers-code-assemble",
    subtitle: "Vibe Coding Hackathon",
    description: "Form your supreme development alliance and engineer disruptive, AI-infused software solutions to solve real-world industry crisis briefs.",
    scope: "college",
    category: "technical",
    type: "squad",
    registrationFee: 200,
    prizePool: 15000,
    difficulty: "expert",
    maxSeats: 25,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "Stark Innovation Labs (MCA Block)",
    coverImage: "/MARVEL/4081455907815375.png",
    hero: "Iron Man & Avengers",
    level: "Level: Alpha",
    powerRating: "Power: 99/100",
    accentColor: "#ED1D24",
    themeGradient: "from-marvel-red/30 to-metallic-gold/10",
    borderClass: "border-marvel-red/40 hover:border-marvel-red",
    glowClass: "hover:shadow-[0_0_40px_rgba(237,29,36,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Prof. Rajesh Kumar", phone: "+91 94470 11111", email: "rajesh@macfast.org" },
    rules: [
      "Team size: 2 to 4 members from recognized colleges/universities.",
      "Projects must be built during the hackathon. Pre-existing codebases are disqualified.",
      "Public GitHub repository commits and live deployment are mandatory for jury evaluation.",
      "Judging criteria: Innovation (30%), Architecture (30%), UI/UX (20%), Defense (20%)."
    ]
  },
  {
    _id: "clg-2",
    title: "The Flash: Code Rush",
    slug: "the-flash-code-rush",
    subtitle: "Coding Challenge",
    description: "Race against the Speed Force in high-octane algorithmic problem sets, rapid debugging sprints, and extreme syntax warfare.",
    scope: "college",
    category: "technical",
    type: "solo",
    registrationFee: 100,
    prizePool: 5000,
    difficulty: "hard",
    maxSeats: 40,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "Turing Lab 2",
    coverImage: "/MARVEL/61080138757668761.png",
    hero: "The Flash",
    level: "Level: Speedster",
    powerRating: "Power: 96/100",
    accentColor: "#FFD700",
    themeGradient: "from-metallic-gold/30 to-marvel-red/10",
    borderClass: "border-metallic-gold/40 hover:border-metallic-gold",
    glowClass: "hover:shadow-[0_0_40px_rgba(255,215,0,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Ananya Nair", phone: "+91 94470 22222", email: "ananya@macfast.org" },
    rules: [
      "Individual participation only.",
      "Languages supported: C, C++, Java, Python, JavaScript.",
      "Score is calculated based on execution speed, test cases cleared, and memory efficiency.",
      "No internet browsing or AI assistants allowed during active coding phases."
    ]
  },
  {
    _id: "clg-3",
    title: "Battle of Wakanda",
    slug: "battle-of-wakanda",
    subtitle: "BGMI Battlegrounds",
    description: "Drop onto the battleground with your elite squad and conquer tactical battle zones to claim the Vibranium Championship Trophy.",
    scope: "college",
    category: "gaming",
    type: "squad",
    registrationFee: 200,
    prizePool: 7000,
    difficulty: "expert",
    maxSeats: 20,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "Asgard Esports Lounge",
    coverImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop",
    hero: "Black Panther",
    level: "Level: Vibranium",
    powerRating: "Power: 98/100",
    accentColor: "#7B2FBE",
    themeGradient: "from-vibranium-purple/30 to-blue-600/10",
    borderClass: "border-vibranium-purple/40 hover:border-vibranium-purple",
    glowClass: "hover:shadow-[0_0_40px_rgba(123,47,190,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Kiran Kumar", phone: "+91 94470 33333", email: "kiran@macfast.org" },
    rules: [
      "Squad participation (4 players + 1 optional sub).",
      "Mobile devices only. Emulators, iPads, triggers, and third-party tools are banned.",
      "Custom room matches across Erangel, Miramar, and Sanhok.",
      "Points awarded based on official BGMI tournament placement and kill multipliers."
    ]
  },
  {
    _id: "clg-4",
    title: "Justice League: Ultimate XI",
    slug: "justice-league-ultimate-xi",
    subtitle: "EFootball Tournament",
    description: "Take command of football titans in head-to-head console and mobile matches. Outwit rival managers and score your way to victory.",
    scope: "college",
    category: "gaming",
    type: "solo",
    registrationFee: 100,
    prizePool: 7000,
    difficulty: "hard",
    maxSeats: 32,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "Esports Arena Console Zone",
    coverImage: "https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=800&auto=format&fit=crop",
    hero: "Justice League",
    level: "Level: League",
    powerRating: "Power: 95/100",
    accentColor: "#00D4FF",
    themeGradient: "from-arc-cyan/30 to-blue-600/10",
    borderClass: "border-arc-cyan/40 hover:border-arc-cyan",
    glowClass: "hover:shadow-[0_0_40px_rgba(0,212,255,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Abhijith R.", phone: "+91 94470 44444", email: "abhijith@macfast.org" },
    rules: [
      "Single elimination knockout bracket.",
      "Match duration: 10 minutes (Extra time and penalties apply on draw).",
      "Authentic clubs & standard team ratings enabled.",
      "Disconnection or intentional stalling leads to forfeit."
    ]
  },
  {
    _id: "clg-5",
    title: "Stark Industries: The Pitch",
    slug: "stark-industries-the-pitch",
    subtitle: "Shark Tank & Startup Pitch",
    description: "Step into the boardroom and pitch breakthrough business models, AI innovations, and venture concepts before seasoned venture investors.",
    scope: "college",
    category: "management",
    type: "duo",
    registrationFee: 150,
    prizePool: 15000,
    difficulty: "expert",
    maxSeats: 16,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "MBA Executive Boardroom",
    coverImage: "/MARVEL/300685712645038155.png",
    hero: "Tony Stark",
    level: "Level: Billionaire",
    powerRating: "Power: 98/100",
    accentColor: "#FFD700",
    themeGradient: "from-metallic-gold/30 to-marvel-red/10",
    borderClass: "border-metallic-gold/40 hover:border-metallic-gold",
    glowClass: "hover:shadow-[0_0_40px_rgba(255,215,0,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Prof. Priya Nair", phone: "+91 94470 55555", email: "priya@macfast.org" },
    rules: [
      "Team size: 1 to 3 delegates.",
      "Pitch deck presentation: 6 minutes + 4 minutes Q&A cross-examination.",
      "Must include business model canvas, revenue stream, TAM/SAM, and prototype/deck.",
      "Panel decision regarding valuations and prize distribution is final."
    ]
  },
  {
    _id: "clg-6",
    title: "Spider-Verse: Frame Hunt",
    slug: "spider-verse-frame-hunt",
    subtitle: "Photography Competition",
    description: "Capture the vibrant soul, energy, and heroic encounters across MACFIESTA through artistic framing, lighting, and storytelling.",
    scope: "college",
    category: "general",
    type: "solo",
    registrationFee: 100,
    prizePool: 5000,
    difficulty: "medium",
    maxSeats: 30,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "Campus Wide Visual Spots",
    coverImage: "/MARVEL/Spider-man.png",
    hero: "Spider-Man",
    level: "Level: Shutter",
    powerRating: "Power: 94/100",
    accentColor: "#ED1D24",
    themeGradient: "from-marvel-red/30 to-blue-600/10",
    borderClass: "border-marvel-red/40 hover:border-marvel-red",
    glowClass: "hover:shadow-[0_0_40px_rgba(237,29,36,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Siddharth Menon", phone: "+91 94470 66666", email: "siddharth@macfast.org" },
    rules: [
      "All photos must be captured on MACFAST campus during festival hours.",
      "DSLR, Mirrorless, and high-end smartphone entries accepted in original RAW/JPEG.",
      "Minor post-processing (color grading, cropping) allowed. AI-generation is banned.",
      "Submission deadline: 4:00 PM on Day 1."
    ]
  },
  {
    _id: "clg-7",
    title: "Deadpool: Reel Chaos",
    slug: "deadpool-reel-chaos",
    subtitle: "Reels Competition",
    description: "Break the fourth wall and create viral, high-voltage short-form video reels that capture the wildest moments and humorous chaos of the fest.",
    scope: "college",
    category: "general",
    type: "duo",
    registrationFee: 100,
    prizePool: 5000,
    difficulty: "medium",
    maxSeats: 30,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "Media Studio / Campus",
    coverImage: "/MARVEL/The Spider….jpg",
    hero: "Deadpool",
    level: "Level: Maximum Effort",
    powerRating: "Power: 95/100",
    accentColor: "#ED1D24",
    themeGradient: "from-marvel-red/30 to-black/40",
    borderClass: "border-marvel-red/40 hover:border-marvel-red",
    glowClass: "hover:shadow-[0_0_40px_rgba(237,29,36,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Rohan Varghese", phone: "+91 94470 77777", email: "rohan@macfast.org" },
    rules: [
      "Reel duration: 30 to 60 seconds (9:16 vertical ratio).",
      "Must tag official @macfiestaofficial handle and use festival audio tags.",
      "Evaluation based on creativity, editing transitions, humor, and engagement.",
      "Submission deadline: 4:30 PM."
    ]
  },
  {
    _id: "clg-8",
    title: "Guardians of the Galaxy: Dance Off",
    slug: "guardians-dance-off",
    subtitle: "Group Dance",
    description: "Bring the groove of the cosmos to the central arena in a synchronized, high-octane group dance battle across diverse dance genres.",
    scope: "college",
    category: "cultural",
    type: "group",
    registrationFee: 150,
    prizePool: 5000,
    difficulty: "hard",
    maxSeats: 12,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "Main Stage Arena",
    coverImage: "https://images.unsplash.com/photo-1547153760-18fc86324498?q=80&w=800&auto=format&fit=crop",
    hero: "Star-Lord & Guardians",
    level: "Level: Cosmic",
    powerRating: "Power: 97/100",
    accentColor: "#7B2FBE",
    themeGradient: "from-vibranium-purple/30 to-arc-cyan/10",
    borderClass: "border-vibranium-purple/40 hover:border-vibranium-purple",
    glowClass: "hover:shadow-[0_0_40px_rgba(123,47,190,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Meera Nair", phone: "+91 94470 88888", email: "meera@macfast.org" },
    rules: [
      "Group size: 6 to 14 dancers.",
      "Time limit: 6 to 8 minutes (including stage setup).",
      "Any style: Hip-Hop, Cinematic, Contemporary, Semi-Classical fusion.",
      "Soundtrack must be submitted on pen drive 1 hour before performance."
    ]
  },
  {
    _id: "clg-9",
    title: "The Dark Knight: Hunt for the Signal",
    slug: "the-dark-knight-hunt-for-the-signal",
    subtitle: "Treasure Hunt",
    description: "Decode cryptic cyphers, navigate secret campus checkpoints, and track down the elusive Bat-Signal before the sands of time run out.",
    scope: "college",
    category: "general",
    type: "squad",
    registrationFee: 200,
    prizePool: 15000,
    difficulty: "expert",
    maxSeats: 25,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "Gotham Campus Perimeter",
    coverImage: "/MARVEL/3025924746959430.jpg",
    hero: "The Dark Knight",
    level: "Level: Detective",
    powerRating: "Power: 100/100",
    accentColor: "#FFD700",
    themeGradient: "from-metallic-gold/30 to-black/50",
    borderClass: "border-metallic-gold/40 hover:border-metallic-gold",
    glowClass: "hover:shadow-[0_0_40px_rgba(255,215,0,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Saji George", phone: "+91 94470 99999", email: "saji@macfast.org" },
    rules: [
      "Team size: 3 to 4 members.",
      "Physical clues and digital AR beacons will be scattered across campus.",
      "Tampering with clues or damaging property results in immediate team elimination.",
      "First team to retrieve the Bat-Signal device and verify at HQ wins the ₹15,000 bounty."
    ]
  },
  {
    _id: "clg-10",
    title: "Batman: Gotham Files",
    slug: "batman-gotham-files",
    subtitle: "Crime Investigation",
    description: "Analyze forensic evidence, interrogate suspicious witnesses, and uncover the criminal mastermind behind Gotham's darkest conspiracy.",
    scope: "college",
    category: "general",
    type: "duo",
    registrationFee: 150,
    prizePool: 7000,
    difficulty: "hard",
    maxSeats: 20,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "Forensic Crime Lab (Room 204)",
    coverImage: "/MARVEL/peakpx.png",
    hero: "Detective Batman",
    level: "Level: Forensic",
    powerRating: "Power: 96/100",
    accentColor: "#00D4FF",
    themeGradient: "from-arc-cyan/30 to-black/40",
    borderClass: "border-arc-cyan/40 hover:border-arc-cyan",
    glowClass: "hover:shadow-[0_0_40px_rgba(0,212,255,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Arun Kurian", phone: "+91 94471 00001", email: "arun@macfast.org" },
    rules: [
      "Team of 2 investigators.",
      "Examine crime scene dossiers, autopsy reports, and coded audio recordings.",
      "Final charge sheet presentation: 15 minutes.",
      "Scoring based on logical deductions, motive identification, and evidence linkage."
    ]
  },
  {
    _id: "clg-11",
    title: "Doctor Strange: Multiverse Escape",
    slug: "doctor-strange-multiverse-escape",
    subtitle: "Escape Room",
    description: "Enter the mystical Sanctum Sanctorum locked by ancient spells. Solve reality-bending spatial puzzles before the dimensional portal collapses.",
    scope: "college",
    category: "general",
    type: "squad",
    registrationFee: 200,
    prizePool: 5000,
    difficulty: "hard",
    maxSeats: 18,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "Sanctum Mystery Chamber (Block B)",
    coverImage: "/MARVEL/Doctor Strange.png",
    hero: "Doctor Strange",
    level: "Level: Mystic",
    powerRating: "Power: 98/100",
    accentColor: "#FF8C00",
    themeGradient: "from-amber-600/30 to-vibranium-purple/15",
    borderClass: "border-amber-500/40 hover:border-amber-500",
    glowClass: "hover:shadow-[0_0_40px_rgba(255,140,0,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Dr. Thomas Varghese", phone: "+91 94471 00002", email: "thomas@macfast.org" },
    rules: [
      "Squad size: 3 to 4 participants.",
      "Maximum escape window: 20 minutes.",
      "No external tools, smartphones, or physical force permitted.",
      "Fastest squad to unlock the portal stone claims 1st place."
    ]
  },
  {
    _id: "clg-12",
    title: "Iron Chef: Battle of Heroes",
    slug: "iron-chef-battle-of-heroes",
    subtitle: "Master Cook",
    description: "Ignite the culinary stoves and craft signature gastronomic masterpieces infused with superhero flair and exquisite plating aesthetics.",
    scope: "college",
    category: "general",
    type: "duo",
    registrationFee: 200,
    prizePool: 5000,
    difficulty: "medium",
    maxSeats: 16,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "Campus Culinary Pavilion",
    coverImage: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?q=80&w=800&auto=format&fit=crop",
    hero: "Iron Chef",
    level: "Level: Gourmet",
    powerRating: "Power: 93/100",
    accentColor: "#ED1D24",
    themeGradient: "from-marvel-red/30 to-metallic-gold/10",
    borderClass: "border-marvel-red/40 hover:border-marvel-red",
    glowClass: "hover:shadow-[0_0_40px_rgba(237,29,36,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Susan Philip", phone: "+91 94471 00003", email: "susan@macfast.org" },
    rules: [
      "Team of 2 culinary chefs.",
      "Preparation time: 60 minutes + 5 minutes plating.",
      "Fireless / induction cooking setups provided. Bring your own spices & secret ingredients.",
      "Judged on taste (40%), presentation & superhero theme (30%), hygiene & innovation (30%)."
    ]
  },
  {
    _id: "clg-13",
    title: "Batman v Superman: Battle of Titans",
    slug: "batman-v-superman-battle-of-titans",
    subtitle: "3v3 Football Turf War",
    description: "Clash in relentless 3v3 mini-football combat on the caged turf. Pure skill, electric speed, and unstoppable teamwork.",
    scope: "college",
    category: "sports",
    type: "squad",
    registrationFee: 200,
    prizePool: 5000,
    difficulty: "hard",
    maxSeats: 24,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "MACFAST Caged Turf Arena",
    coverImage: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?q=80&w=800&auto=format&fit=crop",
    hero: "Superman & Batman",
    level: "Level: Titan",
    powerRating: "Power: 97/100",
    accentColor: "#00D4FF",
    themeGradient: "from-arc-cyan/30 to-marvel-red/10",
    borderClass: "border-arc-cyan/40 hover:border-arc-cyan",
    glowClass: "hover:shadow-[0_0_40px_rgba(0,212,255,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Dr. Mathew John", phone: "+91 94471 00004", email: "mathew@macfast.org" },
    rules: [
      "Team size: 3 players on turf + 1 rolling substitute.",
      "Match duration: 7-1-7 minutes.",
      "No goalkeepers, small target goals. Direct shots only within attacking half.",
      "Direct knockout rules. Penalties (sudden death 1v1) on draw."
    ]
  },
  {
    _id: "clg-14",
    title: "LexCorp vs Stark Industries",
    slug: "lexcorp-vs-stark-industries",
    subtitle: "The Ultimate Marketing Challenge",
    description: "Corporate warfare at its peak. Execute hostile brand takeovers, product launch campaigns, and crisis PR stunts against rival conglomerates.",
    scope: "college",
    category: "management",
    type: "duo",
    registrationFee: 150,
    prizePool: 10000,
    difficulty: "expert",
    maxSeats: 16,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "Management Seminar Hall A",
    coverImage: "/MARVEL/658651514296997716.png",
    hero: "Lex Luthor vs Tony Stark",
    level: "Level: Conglomerate",
    powerRating: "Power: 99/100",
    accentColor: "#10B981",
    themeGradient: "from-emerald-500/30 to-metallic-gold/10",
    borderClass: "border-emerald-500/40 hover:border-emerald-500",
    glowClass: "hover:shadow-[0_0_40px_rgba(16,185,129,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Prof. Ligo Koshy", phone: "+91 94471 00005", email: "ligo@macfast.org" },
    rules: [
      "Team of 2 management executives.",
      "Rounds: Brand Strategy, Crisis Ad Stunt, Hostile Takeover Negotiation.",
      "Time allocated per round: 20 minutes prep + 5 minutes pitch.",
      "Evaluated by industry marketing consultants and executive judges."
    ]
  },

  // ─── SCHOOL EVENTS (8 EVENTS + 1 EXPO = 9 EVENTS) ────────────────
  {
    _id: "sch-1",
    title: "Multiverse: Imagine It",
    slug: "multiverse-imagine-it",
    subtitle: "AI Prompt – Image Creation",
    description: "Harness generative AI prompts to synthesize breathtaking sci-fi, cinematic scenes, and futuristic Marvel concepts from your imagination.",
    scope: "school",
    category: "technical",
    type: "solo",
    registrationFee: 0,
    prizePool: 3000,
    difficulty: "medium",
    maxSeats: 30,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "AI Innovation Lab 1",
    coverImage: "/MARVEL/In a city that never sleeps, I find my….png",
    hero: "Vision & Multiverse",
    level: "Level: Prompt Master",
    powerRating: "Power: 95/100",
    accentColor: "#00D4FF",
    themeGradient: "from-arc-cyan/30 to-vibranium-purple/10",
    borderClass: "border-arc-cyan/40 hover:border-arc-cyan",
    glowClass: "hover:shadow-[0_0_40px_rgba(0,212,255,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Ashwin Kumar", phone: "+91 94471 10001", email: "ashwin@macfast.org" },
    rules: [
      "Open to high school and plus-two students with valid school ID.",
      "Participants will be given 3 mystery theme prompts.",
      "Tools provided on systems. Best creative composition, style coherence, and prompt fidelity wins."
    ]
  },
  {
    _id: "sch-2",
    title: "SpiderLens: Freeze the Moment",
    slug: "spiderlens-freeze-the-moment",
    subtitle: "School Photography",
    description: "Capture the wonder of the festival through young, sharp lenses. Discover candid smiles, dynamic action shots, and festival atmosphere.",
    scope: "school",
    category: "general",
    type: "solo",
    registrationFee: 0,
    prizePool: 3000,
    difficulty: "easy",
    maxSeats: 30,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "Campus Photography Trail",
    coverImage: "/MARVEL/Spider-man.png",
    hero: "Peter Parker SpiderLens",
    level: "Level: Junior Shutter",
    powerRating: "Power: 92/100",
    accentColor: "#ED1D24",
    themeGradient: "from-marvel-red/30 to-arc-cyan/10",
    borderClass: "border-marvel-red/40 hover:border-marvel-red",
    glowClass: "hover:shadow-[0_0_40px_rgba(237,29,36,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Aria Sebastian", phone: "+91 94471 10002", email: "aria@macfast.org" },
    rules: [
      "Individual school participants using smartphones or digital cameras.",
      "Must submit top 2 unedited photos by 3:00 PM.",
      "Judged on creative perspective, lighting, and festival storytelling."
    ]
  },
  {
    _id: "sch-3",
    title: "HeroVerse Dance-Off",
    slug: "heroverse-dance-off",
    subtitle: "Spot Dance Challenge",
    description: "Electrify the spotlight with instant improvised dance moves when the beats drop. No prep, pure groove and rhythm.",
    scope: "school",
    category: "cultural",
    type: "solo",
    registrationFee: 0,
    prizePool: 5000,
    difficulty: "medium",
    maxSeats: 25,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "Sanctum Open Air Stage",
    coverImage: "https://images.unsplash.com/photo-1547153760-18fc86324498?q=80&w=800&auto=format&fit=crop",
    hero: "HeroVerse",
    level: "Level: Spot Rhythm",
    powerRating: "Power: 96/100",
    accentColor: "#7B2FBE",
    themeGradient: "from-vibranium-purple/30 to-marvel-red/10",
    borderClass: "border-vibranium-purple/40 hover:border-vibranium-purple",
    glowClass: "hover:shadow-[0_0_40px_rgba(123,47,190,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Suresh Pillai", phone: "+91 94471 10003", email: "suresh@macfast.org" },
    rules: [
      "Spot dance format — random tracks played by DJ on the spot.",
      "Rounds: Freestyle warm-up, 1v1 face-off, final champion round.",
      "Decided by crowd cheer and jury rating."
    ]
  },
  {
    _id: "sch-4",
    title: "Infinity Quest: Hunt the Stones",
    slug: "infinity-quest-hunt-the-stones",
    subtitle: "School Treasure Hunt",
    description: "Collect all 6 Infinity Stones hidden across safe campus exploration checkpoints through riddles, puzzles, and secret maps.",
    scope: "school",
    category: "general",
    type: "squad",
    registrationFee: 0,
    prizePool: 5000,
    difficulty: "medium",
    maxSeats: 20,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "Sanctum Garden & Library Block",
    coverImage: "/MARVEL/658651514296997716.png",
    hero: "Infinity Gauntlet",
    level: "Level: Gauntlet Quest",
    powerRating: "Power: 97/100",
    accentColor: "#FFD700",
    themeGradient: "from-metallic-gold/30 to-arc-cyan/10",
    borderClass: "border-metallic-gold/40 hover:border-metallic-gold",
    glowClass: "hover:shadow-[0_0_40px_rgba(255,215,0,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Prof. Saji George", phone: "+91 94471 10004", email: "saji@macfast.org" },
    rules: [
      "Team of 3 to 4 school students.",
      "Solve riddles to unlock the next Stone location.",
      "First team to bring all 6 Stones to Avengers Base wins."
    ]
  },
  {
    _id: "sch-5",
    title: "Groot's Green Mission",
    slug: "groots-green-mission",
    subtitle: "Best Out of Waste",
    description: "Transform discarded materials, recyclables, and electronics into functional, artistic, or eco-friendly superhero creations.",
    scope: "school",
    category: "general",
    type: "duo",
    registrationFee: 0,
    prizePool: 3000,
    difficulty: "easy",
    maxSeats: 25,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "Ecology Hall (Block A)",
    coverImage: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?q=80&w=800&auto=format&fit=crop",
    hero: "Groot",
    level: "Level: Eco Marvel",
    powerRating: "Power: 91/100",
    accentColor: "#10B981",
    themeGradient: "from-emerald-500/30 to-metallic-gold/10",
    borderClass: "border-emerald-500/40 hover:border-emerald-500",
    glowClass: "hover:shadow-[0_0_40px_rgba(16,185,129,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Anita Joseph", phone: "+91 94471 10005", email: "anita@macfast.org" },
    rules: [
      "Team of 2 school students.",
      "Bring safe recyclable materials (cardboard, plastic bottles, paper, scrap metal).",
      "Time: 90 minutes. Judged on creativity, environmental message, and presentation."
    ]
  },
  {
    _id: "sch-6",
    title: "Gotham: Mystery Files",
    slug: "gotham-mystery-files",
    subtitle: "Mystery Case / Detective Challenge",
    description: "Step into the shoes of young detective heroes to decipher clues, eliminate red herrings, and solve the locked-room case.",
    scope: "school",
    category: "general",
    type: "duo",
    registrationFee: 0,
    prizePool: 3000,
    difficulty: "medium",
    maxSeats: 25,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "Detective Wing (Room 102)",
    coverImage: "/MARVEL/peakpx.png",
    hero: "Robin & Detective",
    level: "Level: Sleuth",
    powerRating: "Power: 93/100",
    accentColor: "#00D4FF",
    themeGradient: "from-arc-cyan/30 to-black/40",
    borderClass: "border-arc-cyan/40 hover:border-arc-cyan",
    glowClass: "hover:shadow-[0_0_40px_rgba(0,212,255,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Anjali Mathew", phone: "+91 94471 10006", email: "anjali@macfast.org" },
    rules: [
      "Team of 2 school detectives.",
      "Written quiz + case study solving + suspect cross-questioning.",
      "Logical deduction and time to solve will determine the victors."
    ]
  },
  {
    _id: "sch-7",
    title: "Justice League: Mini Clash",
    slug: "justice-league-mini-clash",
    subtitle: "3v3 Football",
    description: "Young football prodigies battle on the mini turf in fast-paced 3v3 action. Agility, teamwork, and sharp striking skills.",
    scope: "school",
    category: "sports",
    type: "squad",
    registrationFee: 0,
    prizePool: 3000,
    difficulty: "medium",
    maxSeats: 16,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "MACFAST Junior Turf",
    coverImage: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?q=80&w=800&auto=format&fit=crop",
    hero: "Justice League Youth",
    level: "Level: Prodigy",
    powerRating: "Power: 94/100",
    accentColor: "#00D4FF",
    themeGradient: "from-arc-cyan/30 to-blue-600/10",
    borderClass: "border-arc-cyan/40 hover:border-arc-cyan",
    glowClass: "hover:shadow-[0_0_40px_rgba(0,212,255,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Kiran Kumar", phone: "+91 94471 10007", email: "kiran@macfast.org" },
    rules: [
      "Team of 3 players + 1 substitute (School students only).",
      "5-1-5 minute halves.",
      "Knockout format. Sports shoes mandatory."
    ]
  },
  {
    _id: "sch-8",
    title: "Superhero Showdown: Speak Your Mind",
    slug: "superhero-showdown-speak-your-mind",
    subtitle: "Debate / Extempore",
    description: "Take the podium and defend moral dilemmas, technological ethics, and superhero ideologies in powerful oratory rounds.",
    scope: "school",
    category: "general",
    type: "solo",
    registrationFee: 0,
    prizePool: 3000,
    difficulty: "medium",
    maxSeats: 25,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "Senate Hall B",
    coverImage: "/MARVEL/Doctor Strange.png",
    hero: "Professor X & Council",
    level: "Level: Orator",
    powerRating: "Power: 95/100",
    accentColor: "#FFD700",
    themeGradient: "from-metallic-gold/30 to-marvel-red/10",
    borderClass: "border-metallic-gold/40 hover:border-metallic-gold",
    glowClass: "hover:shadow-[0_0_40px_rgba(255,215,0,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Prof. Varghese Abraham", phone: "+91 94471 10008", email: "varghese@macfast.org" },
    rules: [
      "Individual participation.",
      "Round 1: Extempore (2 minutes prep, 3 minutes speech).",
      "Round 2: Superhero Debate Face-off.",
      "Judged on eloquence, clarity of thought, rebuttals, and stage presence."
    ]
  },
  {
    _id: "sch-9",
    title: "STARK EXPO — Where Ideas Become Reality",
    slug: "stark-expo-ideas-to-reality",
    subtitle: "AI / Robotics / Science Innovation Expo",
    description: "The grand premier school showcase. Exhibit working science models, robotics prototypes, AI creations, and green engineering inventions.",
    scope: "school",
    category: "technical",
    type: "group",
    registrationFee: 0,
    prizePool: 5000,
    difficulty: "expert",
    maxSeats: 20,
    registeredCount: 0,
    date: "24 Sep 2026",
    time: "10:00 AM onwards",
    venue: "Stark Exhibition Pavilions",
    coverImage: "/MARVEL/4081455907815375.png",
    hero: "Stark Expo Innovations",
    level: "Level: Grand Showcase",
    powerRating: "Power: 100/100",
    accentColor: "#00D4FF",
    themeGradient: "from-arc-cyan/30 to-metallic-gold/15",
    borderClass: "border-arc-cyan/40 hover:border-arc-cyan",
    glowClass: "hover:shadow-[0_0_40px_rgba(0,212,255,0.45)]",
    isLive: true,
    status: "upcoming",
    createdAt: "2026-08-01T00:00:00.000Z",
    coordinator: { name: "Dr. Cherian P. George", phone: "+91 94471 10009", email: "cherian@macfast.org" },
    rules: [
      "Team of 2 to 4 school innovators.",
      "Working prototype, poster board, and demonstration required.",
      "Special Awards for Best Working Robot, Most Sustainable Model, and AI Innovation.",
      "Trophies, Certificates, and recognition for all qualifying schools."
    ]
  }
];

export const EVENTS_BY_SLUG: Record<string, FestivalEventItem> = ALL_EVENTS.reduce((acc, curr) => {
  acc[curr.slug] = curr;
  return acc;
}, {} as Record<string, FestivalEventItem>);
